language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s -c tests/php-unix.ini

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   name: Nette Code Checker
        	php: 7.4
            install:
                - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
            script:
                - php temp/code-checker/code-checker --strict-types


        -   name: Nette Coding Standard
        	php: 7.4
            install:
                - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress
            script:
                - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.yml


        -   stage: Static Analysis (informative)
            script:
                - composer run-script phpstan


        -   stage: Code Coverage
        	php: 7.4
            script:
                - vendor/bin/tester -p phpdbg tests -s -c tests/php-unix.ini --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   stage: Static Analysis (informative)
        -   stage: Code Coverage


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
