<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['test' => 'blockTest'],
	];


	public function main(): array
	{
		extract($this->params);
		echo 'named arguments

';
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		echo '
a) ';
		$this->renderBlock($__nm = 'test', [1, 'var1' => 2] + [], 'html');
		echo '

b) ';
		$this->renderBlock($__nm = 'test', ['var2' => 1] + [], 'html');
		echo '

c) ';
		$this->renderBlock($__nm = 'test', ['hello' => 1] + [], 'html');
		echo '

d) ';
		$this->renderBlock($__nm = 'test', ['var2' => 1, 2] + [], 'html');
		echo ' // invalid';
		return get_defined_vars();
	}


	public function blockTest(array $__args): void
	{
		extract($this->params);
		$var1 = $__args[0] ?? $__args['var1'] ?? null;
		$var2 = $__args[1] ?? $__args['var2'] ?? null;
		$var3 = $__args[2] ?? $__args['var3'] ?? null;
		echo '	Variables ';
		echo LR\Filters::escapeHtmlText($var1) /* line 4 */;
		echo ', ';
		echo LR\Filters::escapeHtmlText($var2) /* line 4 */;
		echo ', ';
		echo LR\Filters::escapeHtmlText($var3) /* line 4 */;
		echo "\n";
	}

}
