<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['test' => 'blockTest'],
	];


	public function main(): array
	{
		extract($this->params);
?>

<?php
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		?>	<?php
		return get_defined_vars();
	}


	public function blockTest(array $__args): void
	{
		extract($__args);
		?>	Parent: <?php echo LR\Filters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) /* line 3 */ ?>/<?php
		echo LR\Filters::escapeHtmlText($this->getReferenceType()) /* line 3 */ ?>

<?php
	}

}
