<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['test' => 'blockTest'],
	];


	public function main(): array
	{
		extract($this->params);
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		echo "\n";
		$this->renderBlock($ʟ_nm = 'test', [1] + [], 'html');
		return get_defined_vars();
	}


	public function blockTest(array $ʟ_args): void
	{

	}

}
