<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'test' => 'blockTest',
		'testargs' => 'blockTestargs',
		'outer' => 'blockOuter',
	];

	public $blockTypes = [
		'test' => 'html',
		'testargs' => 'html',
		'outer' => 'html',
	];


	function main()
	{
		extract($this->params);
?>

<?php
		$var = 10;
?>

<?php
		if ($this->getParentName()) return get_defined_vars();
?>

a) <?php
		$this->renderBlock('test', ['var' => 20] + get_defined_vars(), 'html');
?>



b) <?php
		$this->renderBlock('testargs', [1] + get_defined_vars(), 'html');
?>



g) <?php
		$this->renderBlock('outer', get_defined_vars(), 'html');
?>


<?php
		$var1 = 'outer';
		?>h) <?php
		$this->renderBlock('testargs', get_defined_vars(), 'html');
?>


i) <?php
		$this->renderBlock('testargs', [null] + get_defined_vars(), 'html');
		return get_defined_vars();
	}


	function blockTest($_args)
	{
		extract($_args);
		?>	This is definition #<?php echo LR\Filters::escapeHtmlText($var) /* line 5 */ ?>

<?php
	}


	function blockTestargs($_args)
	{
		extract($this->params);
		list($var1, $var2) = $_args + [NULL, NULL, ];
		?>	Variables <?php echo LR\Filters::escapeHtmlText($var1) /* line 11 */ ?>, <?php echo LR\Filters::escapeHtmlText($var2) /* line 11 */ ?>, <?php
		echo LR\Filters::escapeHtmlText($hello) /* line 11 */ ?>

<?php
	}


	function blockOuter($_args)
	{
		extract($_args);
		$this->renderBlock('testargs', ['hello'] + get_defined_vars(), 'html');

	}

}
