<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'static' => 'blockStatic',
	];

	public $blockTypes = [
		'static' => 'html',
	];


	function main()
	{
		extract($this->params);
		$var = 10;
?>

<?php
		if ($this->getParentName()) return get_defined_vars();
		$this->renderBlock('static', get_defined_vars());
?>


<?php
		$iterations = 0;
		foreach ($iterator = $this->global->its[] = new LR\CachingIterator(['dynamic', 'static']) as $name) {
			$this->checkBlockContentType('html', $name);
			$this->blockQueue[$name][] = [$this, 'blockName'];
			$this->renderBlock($name, get_defined_vars());
?>

<?php
			$iterations++;
		}
		array_pop($this->global->its);
		$iterator = end($this->global->its);
?>

<?php
		$this->renderBlock('dynamic', ['var' => 20] + $this->params, 'html');
?>

<?php
		$this->renderBlock('static', ['var' => 30] + get_defined_vars(), 'html');
?>

<?php
		$this->renderBlock($name . '', ['var' => 40] + $this->params, 'html');
?>

<?php
		$this->checkBlockContentType('html', "word$name");
		$this->blockQueue["word$name"][] = [$this, 'blockWord_name'];
		$this->renderBlock("word$name", get_defined_vars());
?>

<?php
		$this->checkBlockContentType('html', "word$name");
		$this->blockQueue["word$name"][] = [$this, 'blockWord_name_%h%'];
		$this->renderBlock("word$name", get_defined_vars());
?>

<?php
		return get_defined_vars();
	}


	function prepare()
	{
		extract($this->params);
		if (isset($this->params['name'])) trigger_error('Variable $name overwritten in foreach on line 8');

	}


	function blockName($_args)
	{
		extract($_args);
		?>		Dynamic block #<?php echo LR\Filters::escapeHtmlText($var) /* line 10 */ ?>

<?php
	}


	function blockWord_name($_args)
	{
		extract($_args);

	}


	function blockWord_name_%h%($_args)
	{
		extract($_args);

	}


	function blockStatic($_args)
	{
		extract($_args);
		?>	Static block #<?php echo LR\Filters::escapeHtmlText($var) /* line 4 */ ?>

<?php
	}

}
