<?php
%A%

class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%?>
<p>Included file #1</p>

<?php
		/* line 3 */
		$this->createTemplate('include2.latte', ['localvar' => 20] + $this->params, 'include')->renderToContentType('html');
?>

<?php
		/* line 5 */
		$this->createTemplate('../include3.latte', $this->params, 'include')->renderToContentType('html');
?>

<textarea>
pre
</textarea>

Parent: <?php echo LR\Filters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) /* line 11 */ ?>/<?php
		echo LR\Filters::escapeHtmlText($this->getReferenceType()) /* line 11 */ ?>

<?php
%A%
	}

}
