<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['title' => 'blockTitle', 'content' => 'blockContent'],
	];


	public function main(): array
	{
%A%
		ob_start(function () {});
		$this->createTemplate("inc", get_defined_vars(), "includeblock")->renderToContentType('html');
		echo rtrim(ob_get_clean());
		echo "\n";
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		$this->renderBlock('title', get_defined_vars());
		echo "\n";
		$this->renderBlock('content', get_defined_vars());
%A%
	}


	public function prepare(): void
	{
		extract($this->params);
		if (!$this->getReferringTemplate() || $this->getReferenceType() === "extends") {
			foreach (array_intersect_key(['person' => '11'], $this->params) as $__v => $__l) {
				trigger_error("Variable \$$__v overwritten in foreach on line $__l");
			}
		}
		$this->parentName = "parent";
		$this->createTemplate("inc", $this->params, "import")->render();

	}


	public function blockTitle(array $__args): void
	{
		extract($__args);
		echo 'Homepage | ';
		$this->renderBlockParent($__nm = 'title', ($this->hasBlock($__nm, true) ? get_defined_vars() : $this->params));
		$this->renderBlockParent($__nm = 'title', ($this->hasBlock($__nm, true) ? get_defined_vars() : $this->params));

	}


	public function blockContent(array $__args): void
	{
		extract($__args);
		echo '	<ul>
';
		$iterations = 0;
		foreach ($people as $person) {
			echo '		<li>';
			echo LR\Filters::escapeHtmlText($person) /* line 12 */;
			echo '</li>
';
			$iterations++;
		}
		echo '	</ul>
	Parent: ';
		echo LR\Filters::escapeHtmlText(gettype($this->getReferringTemplate())) /* line 15 */;
		echo "\n";
	}

}
