<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'title' => 'blockTitle',
		'content' => 'blockContent',
	];

	public $blockTypes = [
		'title' => 'html',
		'content' => 'html',
	];


	public function main(): array
	{
%A%
		ob_start(function () {});
		$this->createTemplate('inc', get_defined_vars(), 'includeblock')->renderToContentType('html');
		echo rtrim(ob_get_clean());
?>

<?php
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		$this->renderBlock('title', get_defined_vars());
?>

<?php
		$this->renderBlock('content', get_defined_vars());
		?>	<?php
%A%
	}


	public function prepare(): void
	{
		extract($this->params);
		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (['person' => '11'] as $_v => $_l) {
				if (isset($this->params[$_v])) {
					trigger_error("Variable \$$_v overwritten in foreach on line $_l");
				}
			}
		}
		$this->parentName = 'parent';
		$this->createTemplate('inc', $this->params, 'import')->render();

	}


	public function blockTitle(array $_args): void
	{
		extract($_args);
		?>Homepage | <?php
		$this->renderBlockParent('title', get_defined_vars());
		$this->renderBlockParent('title', get_defined_vars());

	}


	public function blockContent(array $_args): void
	{
		extract($_args);
?>
	<ul>
<?php
		$iterations = 0;
		foreach ($people as $person) {
			?>		<li><?php echo LR\Filters::escapeHtmlText($person) /* line 12 */ ?></li>
<?php
			$iterations++;
		}
?>
	</ul>
	Parent: <?php echo LR\Filters::escapeHtmlText(gettype($this->getReferringTemplate())) /* line 15 */ ?>

<?php
	}

}
