<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
%A%
	public function main(): array
	{
		extract($this->params);
?>


<?php ob_start(function () {}) ?>    <?php
		$this->renderBlock('bar', get_defined_vars());
		$__fi = new LR\FilterInfo('html');
		$foo = ob_get_length() ? new LR\Html(ob_get_clean()) : ob_get_clean();
?>

<?php
		$this->renderBlock('content', get_defined_vars());
		return get_defined_vars();
	}
%A%
}
