<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'content' => 'blockContent',
		'title' => 'blockTitle',
		'sidebar' => 'blockSidebar',
	];

	public $blockTypes = [
		'content' => 'html',
		'title' => 'html',
		'sidebar' => 'html',
	];


	public function main(): array
	{
%A%
<?php
		if ($this->getParentName()) return get_defined_vars();
		$this->renderBlock('content', get_defined_vars());
?>

<?php
		$this->renderBlock('sidebar', get_defined_vars());
		?>	<?php
%A%
	}


	public function prepare(): void
	{
		extract($this->params);
		if (!$this->getReferringTemplate() || $this->getReferenceType() === 'extends') {
			foreach (['person' => '8'] as $_v => $_l) {
				if (isset($this->params[$_v])) {
					trigger_error("Variable \$$_v overwritten in foreach on line $_l");
				}
			}
		}
		$this->parentName = 'parent';

	}


	public function blockContent(array $_args): void
	{
		extract($_args);
		?>	<h1><?php
		$this->renderBlock('title', get_defined_vars());
?></h1>

	<ul>
<?php
		$iterations = 0;
		foreach ($people as $person) {
			?>		<li><?php echo LR\Filters::escapeHtmlText($person) /* line 9 */ ?></li>
<?php
			$iterations++;
		}
?>
	</ul>
<?php
	}


	public function blockTitle(array $_args): void
	{
		?>Homepage <?php
	}


	public function blockSidebar(array $_args): void
	{

	}

}
