<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'_outer' => 'blockOuter',
	];

	public $blockTypes = [
		'_outer' => 'html',
	];


	public function main(): array
	{
%A%
		?><div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer')) ?>"><?php $this->renderBlock('_outer', $this->params) ?></div><?php
%A%
	}


	public function prepare(): void
	{
%A%
	}


	public function blockOuter(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer", "static");
		try {
			$iterations = 0;
			foreach (array(1,2,3) as $id) {
				?>		<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id")) ?>"><?php
				$this->global->snippetDriver->enter("inner-$id", "dynamic");
				try {
?>

				#<?php echo LR\Filters::escapeHtmlText($id) /* line 4 */ ?>

<?php
				}
				finally {
					$this->global->snippetDriver->leave();
				}
				?></div><?php
				$iterations++;
			}
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}

}
