<?php
%A%

class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		?><p>Included file #2 (<?php echo LR\Filters::escapeHtmlText($localvar) /* line 1 */ ?>, <?php echo LR\Filters::escapeHtmlText($hello) /* line 1 */ ?>)</p>

Parent: <?php echo LR\Filters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) /* line 3 */ ?>/<?php
		echo LR\Filters::escapeHtmlText($this->getReferenceType()) /* line 3 */ ?>

<?php
%A%
	}

}
