<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public const BLOCKS = [
		'_outer1' => 'blockOuter1',
		'_outer2' => 'blockOuter2',
	];


	public function main(): array
	{
%A%
		?><div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer1')) ?>"><?php $this->renderBlock('_outer1', $this->params) ?></div>

<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer2')) ?>"><?php $this->renderBlock('_outer2', $this->params) ?></div><?php
%A%
	}


	public function prepare(): void
	{
%A%
	}


	public function blockOuter1(array $_args): void
	{
		extract($_args);
		$this->global->snippetDriver->enter("outer1", "static");
		$iterations = 0;
		foreach (array(1,2,3) as $id) {
			?>		<div<?php echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id")) . '"' ?>>
<?php
			$this->global->snippetDriver->enter("inner-$id", "dynamic");
			?>				#<?php echo LR\Filters::escapeHtmlText($id) /* line 4 */ ?>

<?php
			$this->global->snippetDriver->leave();
?>		</div>
<?php
			$iterations++;
		}
		$this->global->snippetDriver->leave();

	}


	public function blockOuter2(array $_args): void
	{
		extract($_args);
		$this->global->snippetDriver->enter("outer2", "static");
		$iterations = 0;
		foreach (array(1,2,3) as $id) {
			?>		<div<?php echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id")) . '"' ?>>
<?php
			$this->global->snippetDriver->enter("inner-$id", "dynamic");
			?>				#<?php echo LR\Filters::escapeHtmlText($id) /* line 13 */ ?>

<?php
			$this->global->snippetDriver->leave();
?>		</div>
<?php
			$iterations++;
		}
		$this->global->snippetDriver->leave();

	}

}
