<?php
%A%

class Template%a% extends Latte\Runtime\Template
{

	function main()
	{
%A%
<?php
		/* line 2 */
		$this->createTemplate('subdir/include1.latte' . '', ['localvar' => 10] + $this->params, "include")->renderToContentType(function ($s, $type) {
			$_fi = new LR\FilterInfo($type);
			return LR\Filters::convertTo($_fi, 'html', $this->filters->filterContent('indent', $_fi, $s));
		});
		return get_defined_vars();
	}

}
