<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'_' => 'block_b14a7',
		'_outer' => 'blockOuter',
		'_inner' => 'blockInner',
		'_title' => 'blockTitle',
		'_title2' => 'blockTitle2',
	];

	public $blockTypes = [
		'_' => 'html',
		'_outer' => 'html',
		'_inner' => 'html',
		'_title' => 'html',
		'_title2' => 'html',
	];


	public function main(): array
	{
%A%
		?><div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('')) ?>"><?php $this->renderBlock('_', $this->params) ?></div>



<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer')) ?>"><?php $this->renderBlock('_outer', $this->params) ?></div>



	@<?php
		if (true) {
			?> Hello World @<?php
		}
?>


	<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('title')) ?>"><?php $this->renderBlock('_title', $this->params) ?></div>

	<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('title2')) ?>"><?php $this->renderBlock('_title2', $this->params) ?></div><?php
		return get_defined_vars();
	}


	public function block_%h%(array $ʟ_args): void
	{
		extract($ʟ_args);
		$this->global->snippetDriver->enter("", "static");
?>

<?php
		$this->global->snippetDriver->leave();

	}


	public function blockOuter(array $ʟ_args): void
	{
		extract($ʟ_args);
		$this->global->snippetDriver->enter("outer", "static");
?>
	Outer
		<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('inner')) ?>"><?php $this->renderBlock('_inner', $this->params) ?></div>
	/Outer
<?php
		$this->global->snippetDriver->leave();

	}


	public function blockInner(array $ʟ_args): void
	{
		extract($ʟ_args);
		$this->global->snippetDriver->enter("inner", "static");
		?>Inner<?php
		$this->global->snippetDriver->leave();

	}


	public function blockTitle(array $ʟ_args): void
	{
		extract($ʟ_args);
		$this->global->snippetDriver->enter("title", "static");
		?>Title 1<?php
		$this->global->snippetDriver->leave();

	}


	public function blockTitle2(array $ʟ_args): void
	{
		extract($ʟ_args);
		$this->global->snippetDriver->enter("title2", "static");
		?>Title 2<?php
		$this->global->snippetDriver->leave();

	}

}
