<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'_outer' => 'blockOuter',
		'_inner' => 'blockInner',
		'_gallery' => 'blockGallery',
	];

	public $blockTypes = [
		'_outer' => 'html',
		'_inner' => 'html',
		'_gallery' => 'html',
	];


	function main()
	{
%A%
		?>	<div class="test"<?php echo ' id="' . htmlSpecialChars($this->global->snippetDriver->getHtmlId('outer')) . '"' ?>>
<?php $this->renderBlock('_outer', []) ?>
	</div>

	<div class="test"<?php echo ' id="' . htmlSpecialChars($this->global->snippetDriver->getHtmlId('inner')) . '"' ?>>
<?php
		$this->renderBlock('_inner', []);
?>	</div>

	<div class="<?php echo LR\Filters::escapeHtmlAttr('class') /* line 9 */ ?>"<?php echo ' id="' . htmlSpecialChars($this->global->snippetDriver->getHtmlId('gallery')) . '"' ?>><?php
		$this->renderBlock('_gallery', []) ?>
</div>
<?php
%A%
	}


	function blockOuter($_args)
	{
		extract($this->params);
		extract($_args);
		$this->global->snippetDriver->enter("outer", "static");
?>	<p>Outer</p>
<?php
		$this->global->snippetDriver->leave();

	}


	function blockInner($_args)
	{
		extract($this->params);
		extract($_args);
		$this->global->snippetDriver->enter("inner", "static");
?>	<p>Inner</p>
<?php
		$this->global->snippetDriver->leave();

	}


	function blockGallery($_args)
	{
		extract($this->params);
		extract($_args);
		$this->global->snippetDriver->enter("gallery", "static");
		$this->global->snippetDriver->leave();

	}

}
