<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		echo '<p>Included file #1</p>

';
		$this->createTemplate("include2.latte", ['localvar' => 20] + $this->params, 'include')->renderToContentType('html') /* line %d% */;
		echo "\n";
		$this->createTemplate("../include3.latte", $this->params, 'include')->renderToContentType('html') /* line %d% */;
		echo '
<textarea>
pre
</textarea>

Parent: ';
		echo LR\Filters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) /* line %d% */;
		echo '/';
		echo LR\Filters::escapeHtmlText($this->getReferenceType()) /* line %d% */;
		echo "\n";
%A%
	}

}
