<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'test' => 'blockTest',
		'true' => 'blockTrue',
	];

	public $blockTypes = [
		'test' => 'html',
		'true' => 'html',
	];


	public function main(): array
	{
		extract($this->params);
		$var = 10;
?>

<?php
		if ($this->getParentName()) {
			return get_defined_vars();
		}
?>

<?php
		$this->renderBlock('test', ['var' => 20] + get_defined_vars(), 'html');
?>

<?php
		$this->renderBlock('true', get_defined_vars(), 'html');
		return get_defined_vars();
	}


	public function blockTest(array $__args): void
	{
		extract($__args);
		?>	This is definition #<?php echo LR\Filters::escapeHtmlText($var) /* line 4 */ ?>

<?php
	}


	public function blockTrue(array $__args): void
	{
		?>true<?php
	}

}
