<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['test' => 'blockTest'],
	];


	public function main(): array
	{
		extract($this->params);
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		echo "\n";
		$this->renderBlock($__nm = 'test', [1] + ($this->hasBlock($__nm, true) ? get_defined_vars() : $this->params), 'html');
		return get_defined_vars();
	}


	public function blockTest(array $__args): void
	{

	}

}
