<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'content' => 'blockContent',
		'title' => 'blockTitle',
		'sidebar' => 'blockSidebar',
	];

	public $blockTypes = [
		'content' => 'html',
		'title' => 'html',
		'sidebar' => 'html',
	];


	public function main(): array
	{
%A%
<?php
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		$this->renderBlock('content', get_defined_vars()) ?>


<?php $this->renderBlock('sidebar', get_defined_vars()) ?>

	<?php
%A%
	}


	public function prepare(): void
	{
		extract($this->params);
		if (!$this->getReferringTemplate() || $this->getReferenceType() === "extends") {
			foreach (array_intersect_key(['person' => '8'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}
		$this->parentName = "parent";

	}


	public function blockContent(array $ʟ_args): void
	{
		extract($ʟ_args);
		?>	<h1><?php $this->renderBlock('title', get_defined_vars()) ?>
</h1>

	<ul>
<?php
		$iterations = 0;
		foreach ($people as $person) {
			?>		<li><?php echo LR\Filters::escapeHtmlText($person) /* line 9 */ ?></li>
<?php
			$iterations++;
		}
?>
	</ul>
<?php
	}


	public function blockTitle(array $ʟ_args): void
	{
		?>Homepage <?php
	}


	public function blockSidebar(array $ʟ_args): void
	{

	}

}
