<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		'content' => 'blockContent',
	];


	public function main(): array
	{
%A%
<?php
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		$this->renderBlock('content', get_defined_vars());
		?>	<?php
%A%
	}


	public function prepare(): void
	{
		extract($this->params);
		$this->parentName = $ext;

	}


	public function blockContent(array $__args): void
	{
?>	Content
<?php
	}

}
