<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
<?php
		/* line 2 */
		$this->createTemplate('subdir/include1.latte' . '', ['localvar' => 10] + $this->params, "include")->renderToContentType(function ($s, $type) {
			$__fi = new LR\FilterInfo($type);
			return LR\Filters::convertTo($__fi, 'html', $this->filters->filterContent('indent', $__fi, $s));
		});
		return get_defined_vars();
	}

}
