<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		['test' => 'blockTest', 'outer' => 'blockOuter'],
	];


	public function main(): array
	{
		extract($this->params);
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		echo '
a) ';
		$this->renderBlock($ʟ_nm = 'test', [1] + [], 'html');
		echo '


b) ';
		$this->renderBlock($ʟ_nm = 'outer', get_defined_vars(), 'html');
		echo '

';
		$var1 = 'outer';
		echo 'c) ';
		$this->renderBlock($ʟ_nm = 'test', [], 'html');
		echo '

d) ';
		$this->renderBlock($ʟ_nm = 'test', [null] + [], 'html');
		return get_defined_vars();
	}


	public function blockTest(array $ʟ_args): void
	{
		extract($this->params);
		$var1 = $ʟ_args[0] ?? $ʟ_args['var1'] ?? null;
		$var2 = $ʟ_args[1] ?? $ʟ_args['var2'] ?? null;
		$var3 = $ʟ_args[2] ?? $ʟ_args['var3'] ?? null;
		echo '	Variables ';
		echo LR\Filters::escapeHtmlText($var1) /* line 2 */;
		echo ', ';
		echo LR\Filters::escapeHtmlText($var2) /* line 2 */;
		echo ', ';
		echo LR\Filters::escapeHtmlText($hello) /* line 2 */;
		echo "\n";
	}


	public function blockOuter(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		$this->renderBlock($ʟ_nm = 'test', ['hello'] + [], 'html');

	}

}
