<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'content' => 'blockContent',
	];

	public $blockTypes = [
		'content' => 'html',
	];


	public function main(): array
	{
%A%
<?php
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		$this->renderBlock('content', get_defined_vars()) ?>
%A%
	}


	public function prepare(): void
	{
		extract($this->params);
		$this->parentName = $ext;

	}


	public function blockContent(array $ʟ_args): void
	{
?>	Content
<?php
	}

}
