<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		'snippet' => ['' => 'block1', 'outer' => 'blockOuter', 'inner' => 'blockInner', 'title' => 'blockTitle', 'title2' => 'blockTitle2'],
	];


	public function main(): array
	{
%A%
		echo '<div id="';
		echo htmlspecialchars($this->global->snippetDriver->getHtmlId(''));
		echo '">';
		$this->renderBlock('', $this->params, null, 'snippet');
		echo '</div>


<div id="';
		echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer'));
		echo '">';
		$this->renderBlock('outer', $this->params, null, 'snippet');
		echo '</div>


	@';
		if (true) {
			echo ' Hello World @';
		}
		echo '

	<div id="';
		echo htmlspecialchars($this->global->snippetDriver->getHtmlId('title'));
		echo '">';
		$this->renderBlock('title', $this->params, null, 'snippet');
		echo '</div>
	<div id="';
		echo htmlspecialchars($this->global->snippetDriver->getHtmlId('title2'));
		echo '">';
		$this->renderBlock('title2', $this->params, null, 'snippet');
		echo '</div>';
		return get_defined_vars();
	}


	public function block1(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("", 'static');
		try {
			echo "\n";
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockOuter(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer", 'static');
		try {
			echo '	Outer
		<div id="';
			echo htmlspecialchars($this->global->snippetDriver->getHtmlId('inner'));
			echo '">';
			$this->renderBlock('inner', $this->params, null, 'snippet');
			echo '</div>	/Outer
';
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockInner(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("inner", 'static');
		try {
			echo 'Inner';
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockTitle(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("title", 'static');
		try {
			echo 'Title 1';
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockTitle2(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("title2", 'static');
		try {
			echo 'Title 2';
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}

}
