<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		'snippet' => ['outer' => 'blockOuter'],
	];


	public function main(): array
	{
%A%
		echo '<div id="';
		echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer'));
		echo '">';
		$this->renderBlock('outer', $this->params, null, 'snippet');
		echo '</div>';
%A%
	}


	public function prepare(): void
	{
%A%
	}


	public function blockOuter(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer", 'static');
		try {
			$iterations = 0;
			foreach (array(1,2,3) as $id) {
				echo '		<div id="';
				echo htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id"));
				echo '">';
				$this->global->snippetDriver->enter("inner-$id", 'dynamic');
				try {
					echo '
				#';
					echo LR\Filters::escapeHtmlText($id) /* line 4 */;
					echo "\n";
				}
				finally {
					$this->global->snippetDriver->leave();
				}
				echo '</div>';
				$iterations++;
			}
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}

}
