<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		0 => ['block1' => 'blockBlock1', 'block2' => 'blockBlock2'],
		'snippet' => ['snippet' => 'blockSnippet', 'outer' => 'blockOuter'],
	];


	public function main(): array
	{
%A%
		$this->renderBlock('block1', get_defined_vars());
		echo '

<div id="';
		echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer'));
		echo '">';
		$this->renderBlock('outer', $this->params, null, 'snippet');
		echo '</div>';
%A%
	}


	public function blockBlock1(array $__args): void
	{
		extract($__args);
		echo '<div';
		echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId('snippet')) . '"';
		echo '>
';
		$this->renderBlock('snippet', $this->params, null, 'snippet');
		echo '</div>
';

	}


	public function blockBlock2(array $__args): void
	{
		extract($__args);
		echo '<div';
		echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId($__nm = "inner-$id")) . '"';
		echo '>
';
		$this->global->snippetDriver->enter($__nm, 'dynamic');
		try {
			echo '		dynamic
';
		}
		finally {
			$this->global->snippetDriver->leave();
		}
		echo '</div>
';

	}


	public function blockSnippet(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("snippet", 'static');
		try {
			echo '		static
';
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockOuter(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer", 'static');
		try {
			echo 'begin
';
			$this->renderBlock('block2', get_defined_vars());
			echo 'end
';
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}

}
