<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		echo '<p>Included file #1</p>

';
		/* line 3 */
		$this->createTemplate("include2.latte", ['localvar' => 20] + $this->params, 'include')->renderToContentType('html');
		echo "\n";
		/* line 5 */
		$this->createTemplate("../include3.latte", $this->params, 'include')->renderToContentType('html');
		echo '
<textarea>
pre
</textarea>

Parent: ';
		echo LR\Filters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) /* line 11 */;
		echo '/';
		echo LR\Filters::escapeHtmlText($this->getReferenceType()) /* line 11 */;
		echo "\n";
%A%
	}

}
