<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		echo '<p>Included file #2 (';
		echo LR\Filters::escapeHtmlText($localvar) /* line 1 */;
		echo ', ';
		echo LR\Filters::escapeHtmlText($hello) /* line 1 */;
		echo ')</p>

Parent: ';
		echo LR\Filters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) /* line 3 */;
		echo '/';
		echo LR\Filters::escapeHtmlText($this->getReferenceType()) /* line 3 */;
		echo "\n";
%A%
	}

}
