<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		ob_start(function () {});
		$this->createTemplate("inc", get_defined_vars(), "includeblock")->renderToContentType('html');
		echo rtrim(ob_get_clean());
		echo "\n";
		$this->renderBlock($__nm = 'test', ($this->hasBlock($__nm, true) ? get_defined_vars() : $this->params), 'html');
%A%
	}

}
