<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		1 => ['a' => 'blockA'],
		2 => ['a' => 'blockA1'],
	];


	public function main(): array
	{
		extract($this->params);
		echo '
		';
		$this->initBlockLayer(1);
		$this->setBlockLayer(1);
		if (false) {
			echo "\n";
			$this->renderBlock('a', get_defined_vars());
			echo '
		';
		}
		try {
			$this->createTemplate("embed1.latte", [], "embed")->renderToContentType('html');
		}
		finally {
			$this->setBlockLayer(0);
		}
		echo '
	';
		return get_defined_vars();
	}


	public function blockA(array $__args): void
	{
		extract($this->params);
		extract($__args);
		echo '				';
		$this->initBlockLayer(2);
		$this->setBlockLayer(2);
		if (false) {
			echo '
					';
			$this->renderBlock('a', get_defined_vars());
			echo '
				';
		}
		try {
			$this->createTemplate("embed2.latte", [], "embed")->renderToContentType('html');
		}
		finally {
			$this->setBlockLayer(1);
		}
		echo "\n";
	}


	public function blockA1(array $__args): void
	{
		echo 'nested embeds A';
	}

}
