<?php
%A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'_outer1' => 'blockOuter1',
		'_outer2' => 'blockOuter2',
	];

	public $blockTypes = [
		'_outer1' => 'html',
		'_outer2' => 'html',
	];


	function render()
	{
%A%

		// main template
		?><div id="<?php echo $this->global->snippetDriver->getHtmlId('outer1') ?>"><?php call_user_func(reset($this->blockQueue['_outer1']), $this->params) ?></div>

<div id="<?php echo $this->global->snippetDriver->getHtmlId('outer2') ?>"><?php call_user_func(reset($this->blockQueue['_outer2']), $this->params) ?></div><?php

	}


	function blockOuter1($_args)
	{
		extract($_args);
		$this->global->snippetDriver->enter("outer1", \Latte\SnippetDriver::TYPE_STATIC);
		$iterations = 0;
		foreach (array(1,2,3) as $id) {
			?>		<div<?php echo ' id="' . $this->global->snippetDriver->getHtmlId("inner-$id") . '"' ?>>
<?php
			$this->global->snippetDriver->enter("inner-$id", \Latte\SnippetDriver::TYPE_DYNAMIC);
			?>				#<?php echo LR\Filters::escapeHtml($id) /* line 4 */ ?>

<?php
			$this->global->snippetDriver->leave();
?>		</div>
<?php
			$iterations++;
		}
		$this->global->snippetDriver->leave();

	}


	function blockOuter2($_args)
	{
		extract($_args);
		$this->global->snippetDriver->enter("outer2", \Latte\SnippetDriver::TYPE_STATIC);
		$iterations = 0;
		foreach (array(1,2,3) as $id) {
			?>		<div<?php echo ' id="' . $this->global->snippetDriver->getHtmlId("inner-$id") . '"' ?>>
<?php
			$this->global->snippetDriver->enter("inner-$id", \Latte\SnippetDriver::TYPE_DYNAMIC);
			?>				#<?php echo LR\Filters::escapeHtml($id) /* line 13 */ ?>

<?php
			$this->global->snippetDriver->leave();
?>		</div>
<?php
			$iterations++;
		}
		$this->global->snippetDriver->leave();

	}

}
