<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		0 => ['block1' => 'blockBlock1', 'block2' => 'blockBlock2'],
		'snippet' => ['snippet' => 'blockSnippet', 'outer' => 'blockOuter'],
	];


	public function main(): array
	{
%A%
		$this->renderBlock('block1', get_defined_vars());
?>


<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer')) ?>"><?php $this->renderBlock('outer', $this->params, null, 'snippet') ?></div><?php
%A%
	}


	public function blockBlock1(array $__args): void
	{
		extract($__args);
		?><div<?php echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId('snippet')) . '"' ?>>
<?php $this->renderBlock('snippet', $this->params, null, 'snippet') ?>
</div>
<?php

	}


	public function blockBlock2(array $__args): void
	{
		extract($__args);
		?><div<?php echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id")) . '"' ?>>
<?php
		$this->global->snippetDriver->enter("inner-$id", 'dynamic');
		try {
?>		dynamic
<?php
		}
		finally {
			$this->global->snippetDriver->leave();
		}
?></div>
<?php

	}


	public function blockSnippet(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("snippet", 'static');
		try {
?>		static
<?php
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockOuter(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer", 'static');
		try {
?>
begin
<?php
			$this->renderBlock('block2', get_defined_vars());
?>
end
<?php
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}

}
