<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		'local' => ['static' => 'blockStatic'],
	];


	public function main(): array
	{
		extract($this->params);
		$var = 10;
		echo "\n";
		if ($this->getParentName()) {
			return get_defined_vars();
		}
		$this->renderBlock('static', get_defined_vars());
		echo '


';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator(['dynamic', 'static'], $ʟ_it ?? null) as $name) {
			$this->addBlock($ʟ_nm = $name, 'html', [[$this, 'blockName']], 'local');
			$this->renderBlock($ʟ_nm, get_defined_vars());
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo "\n";
		$this->renderBlock($ʟ_nm = 'dynamic', ['var' => 20] + [], 'html');
		echo "\n";
		$this->renderBlock($ʟ_nm = 'static', ['var' => 30] + get_defined_vars(), 'html');
		echo "\n";
		$this->renderBlock($ʟ_nm = ($name . ''), ['var' => 40] + [], 'html');
		echo "\n";
		$this->addBlock($ʟ_nm = "word$name", 'html', [[$this, 'blockWord_name']], 'local');
		$this->renderBlock($ʟ_nm, get_defined_vars());
		echo '

';
		$this->addBlock($ʟ_nm = "strip$name", 'html', [[$this, 'blockStrip_name']], 'local');
		$this->renderBlock($ʟ_nm, get_defined_vars(), function ($s, $type) {
			$ʟ_fi = new LR\FilterInfo($type);
			return LR\Filters::convertTo($ʟ_fi, 'html', $this->filters->filterContent('striptags', $ʟ_fi, $s));
		});
		echo "\n";
		return get_defined_vars();
	}


	public function prepare(): void
	{
		extract($this->params);
		if (!$this->getReferringTemplate() || $this->getReferenceType() === "extends") {
			foreach (array_intersect_key(['name' => '8'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}

	}


	public function blockName(array $ʟ_args): void
	{
		extract($ʟ_args);
		echo '		Dynamic block #';
		echo LR\Filters::escapeHtmlText($var) /* line %d% */;
		echo "\n";
	}


	public function blockWord_name(array $ʟ_args): void
	{
		extract($ʟ_args);
		if (false) {
			echo '<div></div>';
		}

	}


	public function blockStrip_name(array $ʟ_args): void
	{
		extract($ʟ_args);
		echo '<span>hello</span>';
	}


	public function blockStatic(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		echo '	Static block #';
		echo LR\Filters::escapeHtmlText($var) /* line %d% */;
		echo "\n";
	}

}
