<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
		extract($this->params);
		echo '
named arguments import

';
		$this->createTemplate("import.latte", $this->params, "import")->render();
		echo '
a) ';
		$this->renderBlock($ʟ_nm = 'test', [1, 'var1' => 2] + [], 'html');
		echo '

b) ';
		$this->renderBlock($ʟ_nm = 'test', ['var2' => 1] + [], 'html');
		echo '

c) ';
		$this->renderBlock($ʟ_nm = 'test', ['hello' => 1] + [], 'html');
		return get_defined_vars();
	}

}
