<?php
%A%
		$iterations = 0;
		foreach ([1, 0] as $cond) /* line %d% */ {
			echo '	';
			echo LR\Filters::escapeHtmlText($cond) /* line %d% */;
			echo "\n";
			ob_start(function () {}) /* line %d% */;
			try {
				echo '		before
';
				if ($cond) /* line %d% */ continue;
				echo '		after
	';
			} finally {
				$ʟ_fi = new LR\FilterInfo('html');
				echo LR\Filters::convertTo($ʟ_fi, 'html', $this->filters->filterContent('upper', $ʟ_fi, $this->filters->filterContent('striphtml', $ʟ_fi, ob_get_clean())));
			}
			echo "\n";
			$iterations++;
		}
%A%
