<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'_outer1' => 'blockOuter1',
		'_outer2' => 'blockOuter2',
	];

	public $blockTypes = [
		'_outer1' => 'html',
		'_outer2' => 'html',
	];


	public function main(): array
	{
%A%
		?><div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer1')) ?>"><?php $this->renderBlock('_outer1', $this->params) ?></div>

<div id="<?php echo htmlspecialchars($this->global->snippetDriver->getHtmlId('outer2')) ?>"><?php $this->renderBlock('_outer2', $this->params) ?></div><?php
%A%
	}


	public function prepare(): void
	{
%A%
	}


	public function blockOuter1(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer1", "static");
		try {
			$iterations = 0;
			foreach (array(1,2,3) as $id) {
				?>		<div<?php echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id")) . '"' ?>>
<?php
				$this->global->snippetDriver->enter("inner-$id", "dynamic");
				try {
					?>				#<?php echo LR\Filters::escapeHtmlText($id) /* line 4 */ ?>

<?php
				}
				finally {
					$this->global->snippetDriver->leave();
				}
?>		</div>
<?php
				$iterations++;
			}
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}


	public function blockOuter2(array $__args): void
	{
		extract($__args);
		$this->global->snippetDriver->enter("outer2", "static");
		try {
			$iterations = 0;
			foreach (array(1,2,3) as $id) {
				?>		<div<?php echo ' id="' . htmlspecialchars($this->global->snippetDriver->getHtmlId("inner-$id")) . '"' ?>>
<?php
				$this->global->snippetDriver->enter("inner-$id", "dynamic");
				try {
					?>				#<?php echo LR\Filters::escapeHtmlText($id) /* line 13 */ ?>

<?php
				}
				finally {
					$this->global->snippetDriver->leave();
				}
?>		</div>
<?php
				$iterations++;
			}
		}
		finally {
			$this->global->snippetDriver->leave();
		}

	}

}
