<?php
%A%
		echo '<ul>
	<li>';
		echo LR\Filters::escapeHtmlText($hello->{'item'}) /* line 2 */;
		echo '</li>
	<li>';
		echo LR\Filters::escapeHtmlText(function(){}) /* line 3 */;
		echo '</li>
	<li>';
		echo LR\Filters::escapeHtmlText(function(){return}) /* line 4 */;
		echo '</li>
	<li>';
		echo LR\Filters::escapeHtmlText(function() {
			return;
		}) /* line 5 */;
		echo '</li>
	<li>';
		echo LR\Filters::escapeHtmlText(($this->filters->upper)(function(){return})) /* line 6 */;
		echo '</li>
	<li>';
		echo LR\Filters::escapeHtmlText(($this->filters->upper)(function() {
			return;
		})) /* line 7 */;
		echo '</li>
	<li>';
		echo LR\Filters::escapeHtmlText(($this->filters->upper)(function() {
			return;
		}, $item->{10})) /* line 8 */;
		echo '</li>
</ul>
%A%
