<?php
%A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		?><span title=<?php echo LR\Filters::escapeHtmlAttrUnquoted($x) ?>></span>

<span title=<?php echo LR\Filters::escapeHtmlAttrUnquoted($x) ?> <?php echo LR\Filters::escapeHtmlAttrUnquoted($x) ?>></span>

<span <?php echo LR\Filters::escapeHtmlAttrUnquoted('title') ?>=<?php echo LR\Filters::escapeHtmlAttrUnquoted($x) ?>></span>
<?php
	}

}
