<?php
%A%

class Template%a% extends Latte\Runtime\Template
{

	function render()
	{
%A%
		?><span title=<?php echo LR\Filters::escapeHtmlAttrUnquoted($x) /* line 1 */ ?>></span>

<span title=<?php echo LR\Filters::escapeHtmlAttrUnquoted($x) /* line 3 */ ?> <?php echo LR\Filters::escapeHtmlAttrUnquoted($x) /* line 3 */ ?>></span>

<span <?php echo LR\Filters::escapeHtmlAttrUnquoted('title') /* line 5 */ ?>=<?php echo LR\Filters::escapeHtmlAttrUnquoted($x) /* line 5 */ ?>></span>
<?php
	}

}
