<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{
	protected const CONTENT_TYPE = 'xml';


	public function main(): array
	{
		extract($this->params);
		if (empty($this->global->coreCaptured) && in_array($this->getReferenceType(), ["extends", null], true)) {
			header('Content-Type: application/xml; charset=utf-8');
		}
		echo '<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/css" href="';
		echo LR\Filters::escapeXml($id) /* line 3 */;
		echo '"?>

<script>';
		if (1) {
			echo '<meta />';
		}
		echo '</script>


<ul>
	<li>Escaped: ';
		echo LR\Filters::escapeXml($hello) /* line 9 */;
		echo '</li>
	<li>Non-escaped: ';
		echo $hello /* line 10 */;
		echo '</li>
	<li>Escaped expression: ';
		echo LR\Filters::escapeXml('<' . 'b' . '>hello' . '</b>') /* line 11 */;
		echo '</li>
	<li>Non-escaped expression: ';
		echo '<' . 'b' . '>hello' . '</b>' /* line 12 */;
		echo '</li>
	<li>Array access: ';
		echo LR\Filters::escapeXml($people[1]) /* line 13 */;
		echo '</li>
	<li>Html: ';
		echo LR\Filters::escapeXml($el) /* line 14 */;
		echo '</li>
</ul>

<style type="text/css">
<!--
#';
		echo LR\Filters::escapeHtmlComment($id) /* line 19 */;
		echo ' {
	background: blue;
}
-->
</style>


<script>
<!--
var html = ';
		echo LR\Filters::escapeHtmlComment($el) /* line 28 */;
		echo ';
-->
</script>


<p onclick =
\'alert(';
		echo LR\Filters::escapeXml($id) /* line 34 */;
		echo ');alert("hello");\'
 title=\'';
		echo LR\Filters::escapeXml($id) /* line 35 */;
		echo '"\'
 style =
 "color:';
		echo LR\Filters::escapeXml($id) /* line 37 */;
		echo ';\'"
 alt=\'';
		echo LR\Filters::escapeXml($el) /* line 38 */;
		echo '\'
 onfocus="alert(';
		echo LR\Filters::escapeXml($el) /* line 39 */;
		echo ')"
>click on me</p>


<!-- ';
		echo LR\Filters::escapeHtmlComment($comment) /* line 43 */;
		echo ' -->


</ul>


<ul>
';
		$iterations = 0;
		foreach ($people as $person) {
			echo '	<li>';
			echo LR\Filters::escapeXml($person) /* line 50 */;
			echo '</li>
';
			$iterations++;
		}
		echo '</ul>

';
		if (true) {
			echo '<p>
	<div><p>true</div>
</p>
';
		}
		echo '
<input/> <input />

<p val = ';
		if (true) {
			echo '"a"';
		}
		else {
			echo '"b"';
		}
		echo '> </p>

<p val = ';
		echo LR\Filters::escapeXmlAttrUnquoted($xss) /* line 61 */;
		echo ' val2=';
		echo LR\Filters::escapeXmlAttrUnquoted($mxss) /* line 61 */;
		echo '> </p>

<p onclick = ';
		echo LR\Filters::escapeXmlAttrUnquoted($xss) /* line 63 */;
		echo '> </p>

<p val = />';
		echo LR\Filters::escapeXml($xss) /* line 65 */;
		echo '</p>
';
		return get_defined_vars();
	}


	public function prepare(): void
	{
		extract($this->params);
		if (!$this->getReferringTemplate() || $this->getReferenceType() === "extends") {
			foreach (array_intersect_key(['person' => '50'], $this->params) as $ʟ_v => $ʟ_l) {
				trigger_error("Variable \$$ʟ_v overwritten in foreach on line $ʟ_l");
			}
		}

	}

}
