<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $contentType = 'ical';


	function render()
	{
%A%
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.org//iCal 4.0.3//CS
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:<?php echo LR\Filters::escapeIcal(call_user_func($this->filters->date, $start, 'Ymd\THis')) /* line 8 */ ?>

DTSTART;TZID=Europe/Prague:<?php echo LR\Filters::escapeIcal(call_user_func($this->filters->date, $start, 'Ymd\THis')) /* line 9 */ ?>

DTEND;TZID=Europe/Prague:<?php echo LR\Filters::escapeIcal(call_user_func($this->filters->date, $end, 'Ymd\THis')) /* line 10 */ ?>

SUMMARY;LANGUAGE=cs:<?php echo LR\Filters::escapeIcal($info) /* line 11 */ ?>

DESCRIPTION:
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
<?php
	}


	function prepare()
	{
		extract($this->params);
		if (empty($this->global->coreCaptured) && in_array($this->getReferenceType(), ["extends", NULL], TRUE)) header('Content-Type: text/calendar; charset=utf-8');
		$start = '2011-06-06';
		$end = '2011-06-07';
		$info = "Hello \"hello\", \nWorld";
		return get_defined_vars();
	}

}
