<?php
%A%
		$iterations = 0;
		foreach ($iterator = $__it = new LR\CachingIterator([0, 1, 2, 3], $__it ?? null) as $item) {
			if ($item % 2) continue;
			echo '	';
			echo LR\Filters::escapeHtmlText($iterator->counter) /* line 4 */;
			echo '. item
';
			$iterations++;
		}
		$iterator = $__it = $__it->getParent();
		echo '
---

';
		$iterations = 0;
		foreach ($iterator = $__it = new LR\CachingIterator([0, 1, 2, 3], $__it ?? null) as $item) {
			if ($item % 2) {
				$iterator->skipRound();
				continue;
			};
			echo '	';
			echo LR\Filters::escapeHtmlText($iterator->counter) /* line 11 */;
			echo '. item
';
			$iterations++;
		}
		$iterator = $__it = $__it->getParent();
		echo '
---

';
		$iterations = 0;
		foreach ($iterator = $__it = new LR\CachingIterator([0, 1, 2, 3], $__it ?? null) as $item) {
			if ($item % 2) break;
			echo '	';
			echo LR\Filters::escapeHtmlText($iterator->counter) /* line 18 */;
			echo '. item
';
			$iterations++;
		}
		$iterator = $__it = $__it->getParent();
%A%
