<?php
%A%
		$iterations = 0;
		foreach (['a', 'b'] as $item) {
			echo '	item
';
			$iterations++;
		}
		echo '
---

';
		$iterations = 0;
		foreach ($iterator = $__it = new LR\CachingIterator(['a', 'b'], $__it ?? null) as $item) {
			echo '	';
			echo LR\Filters::escapeHtmlText($iterator->counter) /* line 9 */;
			echo "\n";
			$iterations++;
		}
		$iterator = $__it = $__it->getParent();
		echo LR\Filters::escapeHtmlText($iterator === null ? 'is null' : null) /* line 11 */;
%A%
