<?php
%A%
		foreach ([1, 1, 2, 3, 3, 3] as $i) {
			echo ' ';
			if (($__loc[1] ?? null) !== ($__tmp = [$i])) {
				$__loc[1] = $__tmp;
				echo ' ';
				echo LR\Filters::escapeHtmlText($i) /* line 2 */;
				echo ' ';
			}
			echo ' ';
			if (($__loc[2] ?? null) !== ($__tmp = ['a', 'b'])) {
				$__loc[2] = $__tmp;
				echo ' const ';
			}
			echo ' ';
			$iterations++;
		}
		echo '

--

';
		$iterations = 0;
		foreach ([1, 1, 2, 3, 3, 3] as $i) {
			echo ' ';
			if (($__loc[3] ?? null) !== ($__tmp = [$i])) {
				$__loc[3] = $__tmp;
				echo ' ';
				echo LR\Filters::escapeHtmlText($i) /* line 6 */;
				echo ' ';
			}
			else {
				echo ' else ';
			}
			echo ' ';
			$iterations++;
		}
		echo '

--

';
		$iterations = 0;
		foreach ([1, 1, 2, 3, 3, 3] as $i) {
			echo ' ';
			ob_start(function () {});
			try {
				echo ' -';
				echo LR\Filters::escapeHtmlText($i) /* line 10 */;
				echo '- ';
			}
			finally {
				$__tmp = ob_get_clean();
			}
			if (($__loc[4] ?? null) !== $__tmp) {
				echo $__loc[4] = $__tmp;
			}
			echo ' ';
			$iterations++;
		}
		echo '

--

';
		$iterations = 0;
		foreach ([1, 1, 2, 3, 3, 3] as $i) {
			echo ' ';
			ob_start(function () {});
			try {
				echo ' -';
				echo LR\Filters::escapeHtmlText($i) /* line 14 */;
				echo '- ';
			}
			finally {
				$__tmp = ob_get_clean();
			}
			if (($__loc[5] ?? null) !== $__tmp) {
				echo $__loc[5] = $__tmp;
			}
			else {
				echo ' else ';
			}
			echo ' ';
			$iterations++;
		}
		echo '

--

';
		$iterations = 0;
		foreach ([1, 1, 2, 3, 3, 3] as $i) {
			echo ' ';
			ob_start(function () {});
			try {
				echo '<span>';
				echo LR\Filters::escapeHtmlText($i) /* line 18 */;
				echo '</span>';
			}
			finally {
				$__tmp = ob_get_clean();
			}
			if (($__loc[6] ?? null) !== $__tmp) {
				echo $__loc[6] = $__tmp;
			}
			$iterations++;
		}
		echo '
--

';
		$iterations = 0;
		foreach ([1, 1, 2, 3, 3, 3] as $i) {
			echo ' ';
			ob_start(function () {});
			try {
				echo '<span class="';
				echo LR\Filters::escapeHtmlAttr($i) /* line 22 */;
				echo '"></span>';
			}
			finally {
				$__tmp = ob_get_clean();
			}
			if (($__loc[7] ?? null) !== $__tmp) {
				echo $__loc[7] = $__tmp;
			}
			$iterations++;
		}
%A%
