<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
?>
<ul>
<?php
		$iterations = 0;
		foreach ($people as $person) {
			?>	<li><?php echo LR\Filters::escapeHtmlText(($this->filters->upper)($person)) /* line 3 */ ?></li>
<?php
			$iterations++;
		}
?>
{* comment latte *}
</ul>

<p>Default: <?php echo LR\Filters::escapeHtmlText($person) /* line 9 */ ?></p>

<p>Default: <?php echo LR\Filters::escapeHtmlText($person) /* line 11 */ ?></p>

<p>Default: <?php echo LR\Filters::escapeHtmlText($person) /* line 13 */ ?></p>

<p>Default: {$person}</p>


{a}
{ {/ {/syntax
<?php
%A%
	}


	public function prepare(): void
	{
%A%
	}

}
