<?php
%A%
final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		echo "\n";
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) /* line %d% */ {
			echo '	';
			if ($iterator->isFirst()) /* line %d% */ {
				echo '(';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast()) /* line %d% */ {
				echo ', ';
			}
			echo ' ';
			if ($iterator->isLast()) /* line %d% */ {
				echo ')';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) /* line %d% */ {
			echo '	';
			if ($iterator->isFirst()) /* line %d% */ {
				echo '(';
			}
			else /* line %d% */ {
				echo '[';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast()) /* line %d% */ {
				echo ', ';
			}
			else /* line %d% */ {
				echo ';';
			}
			echo ' ';
			if ($iterator->isLast()) /* line %d% */ {
				echo ')';
			}
			else /* line %d% */ {
				echo ']';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) /* line %d% */ {
			echo '	';
			if ($iterator->isFirst(2)) /* line %d% */ {
				echo '(';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast(2)) /* line %d% */ {
				echo ', ';
			}
			echo ' ';
			if ($iterator->isLast(2)) /* line %d% */ {
				echo ')';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) /* line %d% */ {
			echo '	';
			if ($iterator->isFirst(1)) /* line %d% */ {
				echo '(';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast(1)) /* line %d% */ {
				echo ', ';
			}
			echo ' ';
			if ($iterator->isLast(1)) /* line %d% */ {
				echo ')';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) /* line %d% */ {
			if ($iterator->isFirst(0)) /* line %d% */ {
				echo '	<span>(</span>';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast()) /* line %d% */ {
				echo '<span>, </span>';
			}
			echo ' ';
			if ($iterator->isLast()) /* line %d% */ {
				echo '<span>)</span>
';
			}
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
%A%
	}


	public function prepare(): void
	{
%A%
	}

}
