<?php
%A%
		$ʟ_switch = (0);
		if (false) {
		}
		elseif (in_array($ʟ_switch, [''], true)) {
			echo 'string
';
		}
		elseif (in_array($ʟ_switch, [0.0], true)) {
			echo 'flot
';
		}
		else {
			echo 'def
';
		}
		echo '
---

';
		$ʟ_switch = ('a');
		if (false) {
		}
		elseif (in_array($ʟ_switch, [1, 2, 'a'], true)) {
			echo 'a
';
		}
		echo '
---

';
		$ʟ_switch = ('a');
		if (false) {
		}
		else {
			echo 'def
';
		}
		echo '
---

';
		$ʟ_switch = ('a');
		if (false) {
		}
%A%
