<?php
%A%
		foreach ($iterator = $ʟ_it = new LR\CachingIterator([0, 1, 2, 3], $ʟ_it ?? null) as $item) {
			echo '	pre ';
			echo LR\Filters::escapeHtmlText($item) /* line 3 */;
			echo "\n";
			do {
				echo '		inner ';
				echo LR\Filters::escapeHtmlText($item) /* line 5 */;
				echo "\n";

				if (!$iterator->hasNext()) {
					break;
				}
				$iterator->next();
				[, $item] = [$iterator->key(), $iterator->current()];
			}
			while (true);
			echo '	post ';
			echo LR\Filters::escapeHtmlText($item) /* line 7 */;
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '
---

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator([0, 1, 2, 3], $ʟ_it ?? null) as $item) {
			echo '	pre ';
			echo LR\Filters::escapeHtmlText($item) /* line 13 */;
			echo "\n";
			do {
				if (!$iterator->hasNext() || !($item % 2)) {
					break;
				}
				$iterator->next();
				[, $item] = [$iterator->key(), $iterator->current()];
				echo '		inner ';
				echo LR\Filters::escapeHtmlText($item) /* line 15 */;
				echo "\n";
			}
			while (true);
			echo '	post ';
			echo LR\Filters::escapeHtmlText($item) /* line 17 */;
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '
---

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator([0, 1, 2, 3], $ʟ_it ?? null) as $item) {
			echo '	pre ';
			echo LR\Filters::escapeHtmlText($item) /* line 23 */;
			echo "\n";
			do {
				echo '		inner ';
				echo LR\Filters::escapeHtmlText($item) /* line 25 */;
				echo "\n";

				if (!$iterator->hasNext() || !($item % 2)) {
					break;
				}
				$iterator->next();
				[, $item] = [$iterator->key(), $iterator->current()];
			}
			while (true);
			echo '	post ';
			echo LR\Filters::escapeHtmlText($item) /* line 27 */;
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '
---

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator(['a' => [0], 'b' => [1], 'c' => [2]], $ʟ_it ?? null) as $key => [$i]) {
			echo '	pre ';
			echo LR\Filters::escapeHtmlText($key) /* line 33 */;
			echo ' ';
			echo LR\Filters::escapeHtmlText($i) /* line 33 */;
			echo "\n";
			do {
				echo '		inner ';
				echo LR\Filters::escapeHtmlText($key) /* line 35 */;
				echo ' ';
				echo LR\Filters::escapeHtmlText($i) /* line 35 */;
				echo "\n";

				if (!$iterator->hasNext() || !(true)) {
					break;
				}
				$iterator->next();
				[$key ,  [$i]] = [$iterator->key(), $iterator->current()];
			}
			while (true);
			echo '	post ';
			echo LR\Filters::escapeHtmlText($key) /* line 37 */;
			echo ' ';
			echo LR\Filters::escapeHtmlText($i) /* line 37 */;
			echo "\n";
			$iterations++;
		}
%A%
