<?php
%A%
		if (true) {
			echo '	a
';
		}
		elseif ($b) {
			echo '	b
';
		}
		elseif (isset($c)) {
			echo '	c
';
		}
		else {
			echo '	d
';
		}
		echo '
--

';
		ob_start(function () {});
		echo '	a
';
		if (true) echo ob_get_clean();
		else ob_end_clean();
		echo '

--

';
		ob_start(function () {});
		echo '	a
';
		ob_start(function () {});
		echo '	d
';
		if (true) {
			ob_end_clean();
			echo ob_get_clean();
		}
		else {
			$__tmp = ob_get_clean();
			ob_end_clean();
			echo $__tmp;
		}
		echo '

--

';
		if (isset($a)) {
			echo '	a
';
		}
		elseif ($b) {
			echo '	b
';
		}
		elseif (isset($c)) {
			echo '	c
';
		}
		else {
			echo '	d
';
		}
%A%
