<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		echo '<ul>
';
		$iterations = 0;
		foreach ($people as $person) {
			echo '	<li>';
			echo LR\Filters::escapeHtmlText(($this->filters->upper)($person)) /* line 3 */;
			echo '</li>
';
			$iterations++;
		}
		echo '{* comment latte *}
</ul>

<p>Default: ';
		echo LR\Filters::escapeHtmlText($person) /* line 9 */;
		echo '</p>

<p>Default: ';
		echo LR\Filters::escapeHtmlText($person) /* line 11 */;
		echo '</p>

<p>Default: ';
		echo LR\Filters::escapeHtmlText($person) /* line 13 */;
		echo '</p>

<p>Default: {$person}</p>


{a}
{ {/ {/syntax
';
		return get_defined_vars();
	}


	public function prepare(): void
	{
%A%
	}

}
