<?php
%A%

final class Template%a% extends Latte\Runtime\Template
{

	public function main(): array
	{
%A%
		echo "\n";
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) {
			echo '	';
			if ($iterator->isFirst()) {
				echo '(';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast()) {
				echo ', ';
			}
			echo ' ';
			if ($iterator->isLast()) {
				echo ')';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) {
			echo '	';
			if ($iterator->isFirst()) {
				echo '(';
			}
			else {
				echo '[';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast()) {
				echo ', ';
			}
			else {
				echo ';';
			}
			echo ' ';
			if ($iterator->isLast()) {
				echo ')';
			}
			else {
				echo ']';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) {
			echo '	';
			if ($iterator->isFirst(2)) {
				echo '(';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast(2)) {
				echo ', ';
			}
			echo ' ';
			if ($iterator->isLast(2)) {
				echo ')';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) {
			echo '	';
			if ($iterator->isFirst(1)) {
				echo '(';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast(1)) {
				echo ', ';
			}
			echo ' ';
			if ($iterator->isLast(1)) {
				echo ')';
			}
			echo "\n";
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '

';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator($people, $ʟ_it ?? null) as $person) {
			if ($iterator->isFirst(0)) {
				echo '	<span>(</span>';
			}
			echo ' ';
			echo LR\Filters::escapeHtmlText($person) /* line %d% */;
			if (!$iterator->isLast()) {
				echo '<span>, </span>';
			}
			echo ' ';
			if ($iterator->isLast()) {
				echo '<span>)</span>
';
			}
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
%A%
	}


	public function prepare(): void
	{
%A%
	}

}
