<?php
%A%
		$ʟ_try[0] = [ob_get_level(), $ʟ_it ?? null];
		ob_start(function () {});
		try /* line %d% */ {
			echo '	a
';
			throw new LR\RollbackException;
			echo '	b
';
			echo ob_get_clean();
		} catch (\Throwable $ʟ_e) {
			$iterator = $ʟ_it = $ʟ_try[0][1];
			while (ob_get_level() > $ʟ_try[0][0]) ob_end_clean();
			if (!($ʟ_e instanceof LR\RollbackException) && isset($this->global->coreExceptionHandler)) {
				($this->global->coreExceptionHandler)($ʟ_e, $this);
			}
			echo '	c
';
		}
%A%
