<?php
%A%
		while ($i++ < 10) /* line %d% */ {
			echo '	';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			echo "\n";
		}
		echo '

';
		do /* line %d% */ {
			echo '	';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			echo "\n";
		}
		while ($i++ < 10);
		echo '

';
		while ($i++ < 10) /* line %d% */ {
			if (true) /* line %d% */ break;
			if (true) /* line %d% */ continue;
			echo '	';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			echo "\n";
		}
%A%
