<?php
%A%
		echo '
<ul title="foreach break">
';
		$iterations = 0;
		foreach ([0, 1, 2, 3] as $i) {
			echo '	<li>';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			if (true) {
				echo "</li>\n";
				break;
			}
			echo '</li>
';
			$iterations++;
		}
		echo '</ul>

<ul title="foreach continue">
';
		$iterations = 0;
		foreach ([0, 1, 2, 3] as $i) {
			echo '	<li>';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			if (true) {
				echo "</li>\n";
				continue;
			}
			echo '</li>
';
			$iterations++;
		}
		echo '</ul>

<ul title="foreach skip">
';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator([0, 1, 2, 3], $ʟ_it ?? null) as $i) {
			echo '	<li>';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			if (true) {
				echo "</li>\n";
				{
					$iterator->skipRound();
					continue;
				};
			}
			echo '</li>
';
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '</ul>


<ul title="inner foreach break">
	<li>';
		$iterations = 0;
		foreach ([0, 1, 2, 3] as $i) {
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			if (true) break;
			$iterations++;
		}
		echo '</li>
</ul>

<ul title="inner foreach continue">
	<li>';
		$iterations = 0;
		foreach ([0, 1, 2, 3] as $i) {
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			if (true) continue;
			$iterations++;
		}
		echo '</li>
</ul>

<ul title="inner foreach skip">
	<li>';
		$iterations = 0;
		foreach ($iterator = $ʟ_it = new LR\CachingIterator([0, 1, 2, 3], $ʟ_it ?? null) as $i) {
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			if (true) {
				$iterator->skipRound();
				continue;
			};
			$iterations++;
		}
		$iterator = $ʟ_it = $ʟ_it->getParent();
		echo '</li>
</ul>
';
%A%
