<?php
%A%
	public function main(): array
	{
		extract($this->params);
		/** @var mixed $a (ExampleTemplateType) */
		/** @var int $b (ExampleTemplateType) */
		/** @var ?ExampleTemplateType $c (ExampleTemplateType) */
%A%
	public function blockTest(array $ʟ_args): void
	{
		extract($this->params);
		/** @var mixed $a (ExampleTemplateType) */
		/** @var int $b (ExampleTemplateType) */
		/** @var ?ExampleTemplateType $c (ExampleTemplateType) */
%A%