<?php
%A%
		while ($i++ < 10) {
			echo '	';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			echo "\n";
		}
		echo '

';
		do {
			echo '	';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			echo "\n";
		}
		while ($i++ < 10);
		echo '

';
		while ($i++ < 10) {
			if (true) break;
			if (true) continue;
			echo '	';
			echo LR\Filters::escapeHtmlText($i) /* line %d% */;
			echo "\n";
		}
%A%
