<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $contentType = 'ical';


	function render()
	{
%A%
		header('Content-Type: text/calendar; charset=utf-8');
		$start = '2011-06-06';
		$end = '2011-06-07';
		$info = "Hello \"hello\", \nWorld" ?>
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//example.org//iCal 4.0.3//CS
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:<?php echo LFilters::escapeIcal(call_user_func($this->filters->date, $start, 'Ymd\THis')) ?>

DTSTART;TZID=Europe/Prague:<?php echo LFilters::escapeIcal(call_user_func($this->filters->date, $start, 'Ymd\THis')) ?>

DTEND;TZID=Europe/Prague:<?php echo LFilters::escapeIcal(call_user_func($this->filters->date, $end, 'Ymd\THis')) ?>

SUMMARY;LANGUAGE=cs:<?php echo LFilters::escapeIcal($info) ?>

DESCRIPTION:
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
<?php
	}

}
