<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'title' => 'blockTitle',
		'sidebar' => 'blockSidebar',
	];

	public $blockTypes = [
		'title' => 'html',
		'sidebar' => 'html',
	];


	function render()
	{

		// prolog Latte\Macros\CoreMacros
		if ($this->initialize($_args)) return;
		extract($_args);

		// main template
		?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="stylesheet" href="style.css">
	<title><?php
		call_user_func(reset($this->blockQueue['title']), get_defined_vars());
		?></title>
</head>

<body>
	<div id="sidebar">
<?php
		call_user_func(reset($this->blockQueue['sidebar']), get_defined_vars());
		?>
	</div>

	<div id="content">
<?php
		if ('html' !== $this->blockTypes['content']) {
			trigger_error('Incompatible context for including block content.', E_USER_WARNING);
		}
		$this->renderBlock('content', $this->params) ?>
	</div>
</body>
</html>
Parent: <?php echo LFilters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) ?>/<?php
		echo LFilters::escapeHtmlText($this->getReferenceType()) ?>

<?php
	}


	function prepare()
	{
		extract($this->params);
		extract(['class' => NULL, 'namespace' => NULL, 'top' => TRUE], EXTR_SKIP);
		return get_defined_vars();
	}


	function blockTitle($_args)
	{
		?>My website<?php
	}


	function blockSidebar($_args)
	{
		?>		<ul>
			<li><a href="/">Homepage</a></li>
			<li><a href="/contact">Contact</a></li>
		</ul>
<?php
	}

}
