<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $_blocks = [
		'title' => 'block_title_d5d3db1',
		'content' => 'block_content_9a0364b',
	];


	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
// template extending

$_l->extends = "inheritance.parent.latte"; $_g->extended = TRUE;

if ($_l->extends) { ob_start(function () {});}

// main template ?>

<?php ob_start(function () {}); $_g->includingBlock = isset($_g->includingBlock) ? ++$_g->includingBlock : 1; $this->renderChildTemplate('includeblock.inc.latte', get_defined_vars()); $_g->includingBlock--; echo rtrim(ob_get_clean()) ?>


<?php if ($_l->extends) { ob_end_clean(); return $this->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_b->blocks['title']), $_b, get_defined_vars())  ?>

<?php call_user_func(reset($_b->blocks['content']), $_b, get_defined_vars()) ;
	}


	function block_title_%h%($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v
?>Homepage | <?php Latte\Macros\BlockMacrosRuntime::callBlockParent($_b, 'title', get_defined_vars()) ;Latte\Macros\BlockMacrosRuntime::callBlockParent($_b, 'title', get_defined_vars()) ;
	}


	function block_content_%h%($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v
?>	<ul>
<?php %a% foreach ($people as $person) { ?>
		<li><?php echo LFilters::escapeHtmlText($person) ?></li>
<?php $iterations++; } ?>
	</ul>
<?php
	}

}
