<?php
// source: %a%
%A%
// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $template->initialize('%[a-z0-9]+%', 'xhtml')
;
// prolog Latte\Macros\BlockMacros
//
// block menu
//
if (!function_exists($_b->blocks['menu'][] = '_%[a-z0-9]+%_menu')) { function _%[a-z0-9]+%_menu($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?><ul>
<?php $iterations = 0; if (isset($template->item)) trigger_error('Variable $item overwritten in foreach.', E_USER_NOTICE); foreach ($iterator = $_l->its[] = new Latte\Runtime\CachingIterator($menu) as $item) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($counter++) ?> <?php if (is_array($item)) { ?>
 <?php call_user_func(reset($_b->blocks['menu']), $_b, ['menu' => $item] + get_defined_vars()) ?>
 <?php } else { echo Latte\Runtime\Filters::escapeHtmlText($item) ;} ?></li>
<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>
</ul>
<?php
}}

//
// block bl
//
if (!function_exists($_b->blocks['bl'][] = '_%[a-z0-9]+%_bl')) { function _%[a-z0-9]+%_bl($_b, $_args) { foreach ($_args as $__k => $__v) $$__k = $__v
?><ul title="block + if + foreach">
<?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { if (strlen($person)===4) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ?></li>
<?php } $iterations++; } ?>
</ul>
<?php
}}

//
// end of blocks
//

// template extending

$_l->extends = empty($_g->extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $_g->extended = TRUE;

if ($_l->extends) { ob_start(function () {});}

//
// main template
//
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ul>
	<li>Escaped: <?php echo Latte\Runtime\Filters::escapeHtmlText($hello) ?></li>
	<li>Non-escaped: <?php echo $hello ?></li>
	<li>Escaped expression: <?php echo Latte\Runtime\Filters::escapeHtmlText('<' . 'b' . '>hello' . '</b>') ?></li>
	<li>Non-escaped expression: <?php echo '<' . 'b' . '>hello' . '</b>' ?></li>
	<li>Array access: <?php echo Latte\Runtime\Filters::escapeHtmlText($people[1]) ?></li>
	<li>Html: <?php echo Latte\Runtime\Filters::escapeHtmlText($el) ?></li>
	<li>Translated: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->translate($people[1])) ?></li>
	<li>Translated string: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->translate('ahoj')) ?></li>
	<li>Non-escaped and translated: <?php echo $template->translate($people[1]) ?></li>
	<li>Condition: <?php echo Latte\Runtime\Filters::escapeHtmlText($hello ? 'yes' : NULL) ?>
 <?php echo Latte\Runtime\Filters::escapeHtmlText($hello ? 'yes' : NULL) ?></li>
	<li>Array: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->join($hello ? ['a', 'b', 'c'] : NULL)) ?>
 <?php echo Latte\Runtime\Filters::escapeHtmlText($template->join(['a', 'b', $hello ? 'c' : NULL])) ?></li>
</ul>

<input /> <input /> <input />

<input checked /> <input checked="checked" />

{ test} {"test} {'test}

<p<?php echo Latte\Runtime\Filters::htmlAttributes(['title' => $hello, 'lang' => isset($lang) ? $lang : NULL]) ?>> </p>

<p val = <?php if (true) { ?>"a"<?php } else { ?>"b"<?php } ?>> </p>

<p val0 val1 = tmp val2=tmp val3="x"></p> </p>

<p val = <?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr($xss), '"' ?> val2=<?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr($mxss), '"' ?>> </p>

<p onclick = <?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr(Latte\Runtime\Filters::escapeJs($xss)), '"' ?>> </p>

<p ONCLICK ="<?php echo Latte\Runtime\Filters::escapeHtmlAttr(Latte\Runtime\Filters::escapeJs($xss)) ?>
" <?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr($xss), '"' ?>> </p>

<p val = /><?php echo Latte\Runtime\Filters::escapeHtmlText($xss) ?></p>

<?php echo Latte\Runtime\Filters::escapeHtmlText((string) (bool) (float) (int) (array) 10) ?>


<?php if ($hello) { ?>
	<?php echo Latte\Runtime\Filters::escapeHtmlText($hello) ?>

<?php } elseif ($any) { ?>
	<?php echo Latte\Runtime\Filters::escapeHtmlText($any) ?>

<?php } else { ?>
	none
<?php } ?>


<?php $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ($iterator = $_l->its[] = new Latte\Runtime\CachingIterator(array(TRUE)) as $foo) { $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($iterator = $_l->its[] = new Latte\Runtime\CachingIterator($people) as $person) { ?>
	<?php if ($iterator->isFirst()) { ?><ul><?php } ?>

	<li id="item-<?php echo Latte\Runtime\Filters::escapeHtmlAttr($iterator->getCounter()) ?>
" class="<?php echo Latte\Runtime\Filters::escapeHtmlAttr($iterator->isOdd() ? 'odd' : 'even') ?>
"><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ?></li>
	<?php if ($iterator->isLast()) { ?></ul><?php } ?>

<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ;$iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>



<STYLE type="text/css">
<!--
#<?php echo Latte\Runtime\Filters::escapeCss($xss) ?> {
	background: blue;
}
-->
</style>



<script>
<!--
alert('</div>');

var prop = <?php echo Latte\Runtime\Filters::escapeJs($people) ?>;

document.getElementById(<?php echo Latte\Runtime\Filters::escapeJs($xss) ?>).style.backgroundColor = 'red';

var html = <?php echo Latte\Runtime\Filters::escapeJs($el) ?>;
-->
</script>


<SCRIPT>
/* <![CDATA[ */

var prop2 = <?php echo Latte\Runtime\Filters::escapeJs($people) ?>;

/* ]]> */
</script>


<p onclick =
'alert(<?php echo Latte\Runtime\Filters::escapeHtmlAttr(Latte\Runtime\Filters::escapeJs($xss)) ?>);alert("hello");'
 title='<?php echo Latte\Runtime\Filters::escapeHtmlAttr($xss) ?>'
 STYLE =
 "color:<?php echo Latte\Runtime\Filters::escapeHtmlAttr(Latte\Runtime\Filters::escapeCss($xss)) ?>;"
 rel="<?php echo Latte\Runtime\Filters::escapeHtmlAttr($xss) ?>"
 onblur="alert(<?php echo Latte\Runtime\Filters::escapeHtmlAttr(Latte\Runtime\Filters::escapeJs($xss)) ?>)"
 alt='<?php echo Latte\Runtime\Filters::escapeHtmlAttr($el) ?>'
 onfocus="alert(<?php echo Latte\Runtime\Filters::escapeHtmlAttr(Latte\Runtime\Filters::escapeJs($el)) ?>)"
>click on me <?php echo Latte\Runtime\Filters::escapeHtmlText($xss) ?></p>



<?php $counter = 0 ;if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_b->blocks['menu']), $_b, get_defined_vars())  ?>


<?php extract(['varx' => 2], EXTR_SKIP) ;echo Latte\Runtime\Filters::escapeHtmlText($varx) ?>

<?php extract(['varx' => 4], EXTR_SKIP) ;echo Latte\Runtime\Filters::escapeHtmlText($varx) ?>


<?php $varx = 8 ;echo Latte\Runtime\Filters::escapeHtmlText($varx) ?>

<?php $varx = 9 ;echo Latte\Runtime\Filters::escapeHtmlText($varx) ?>


<?php $now = new DateTime ;$foo = $now->format('u') ;extract(['foo' => $now->format('u')], EXTR_SKIP) ?>



</ul>


<ul title="foreach">
<?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ?></li>
<?php $iterations++; } ?>
</ul>

<ul title="for">
<?php for ($i=0;$i<3;$i++) { ?>	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($i) ?></li>
<?php } ?>
</ul>

<ul title="white">
<?php while (--$i>0) { ?>	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($i) ?></li>
<?php } ?>
</ul>

<?php if (true) { ?><p>
	<div><p>true</div>
</p>
<?php } ?>

<?php if (true) { ?><p>
	<div><p>true</p></div>
</p>
<?php } ?>

<?php if (false) { ?><p>
	<div><p>false</div>
</p>
<?php } ?>

<?php if (false) { ?><p>
	<div><p>false</p></div>
</p>
<?php } ?>

<?php if (strlen('{$xss}') > 5) { ?><p>noLatte</p>
<?php } ?>

<ul title="if + foreach">
<?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { if (strlen($person)===4) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ?></li>
<?php } $iterations++; } ?>
</ul>

<ul title="if + inner-if + inner-foreach">
<?php if (empty($iterator)) { ?>	<li><?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { if (strlen($person)===4) { echo Latte\Runtime\Filters::escapeHtmlText($person) ;} $iterations++; } ?></li>
<?php } ?>
</ul>

<ul title="inner-if + inner-foreach">
<?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { if (strlen($person)===4) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->lower($person)) ?></li>
<?php } $iterations++; } ?></ul>

<?php call_user_func(reset($_b->blocks['bl']), $_b, get_defined_vars())  ?>

<?php if ($_l->ifs[] = (true)) { ?><b><?php } ?>
bold<?php if (array_pop($_l->ifs)) { ?></b><?php } ?>
 <?php if ($_l->ifs[] = (false)) { ?><b><?php } ?>
normal<?php if (array_pop($_l->ifs)) { ?></b>
<?php } ?>

<?php if ($_l->ifs[] = (true)) { ?><b<?php if ($_l->tmp = array_filter(['first'])) echo ' class="', Latte\Runtime\Filters::escapeHtmlAttr(implode(" ", array_unique($_l->tmp))), '"' ?>
><?php } ?>
bold<?php if (array_pop($_l->ifs)) { ?></b>
<?php } ?>

<?php echo 'test' ?>


{ }

<p<?php if ($_l->tmp = array_filter(['foo', (false ? 'first' : NULL), 'odd', ($hello ? 'foo' : 'bar')])) echo ' class="', Latte\Runtime\Filters::escapeHtmlAttr(implode(" ", array_unique($_l->tmp))), '"' ?>>n:class</p>

<p<?php if ($_l->tmp = array_filter([false ? 'first' : NULL])) echo ' class="', Latte\Runtime\Filters::escapeHtmlAttr(implode(" ", array_unique($_l->tmp))), '"' ?>>n:class empty</p>

<meta />
<?php if (true) { ?><meta />
<?php } if ($_l->ifs[] = (true)) { ?><meta />
<?php } if (array_pop($_l->ifs)) { } ?>
<meta />
<?php if (true) { } ?><meta />

<?php ob_start(function () {}) ?>TRUE<?php if (TRUE) echo ob_get_clean(); else ob_end_clean() ?>

<?php ob_start(function () {}) ?>FALSE<?php if (FALSE) echo ob_get_clean(); else ob_end_clean() ?>

<?php ob_start(function () {}) ?>TRUE<?php ob_start(function () {}) ?>FALSE<?php if (TRUE) { ob_end_clean(); echo ob_get_clean(); } else { $_l->else = ob_get_clean(); ob_end_clean(); echo $_l->else; } ?>


<?php $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ($iterator = $_l->its[] = new Latte\Runtime\CachingIterator([1,2,3]) as $foo) { ?>
	<b<?php if ($_l->tmp = array_filter([$iterator->even ? 'even' : NULL])) echo ' class="', Latte\Runtime\Filters::escapeHtmlAttr(implode(" ", array_unique($_l->tmp))), '"' ?>>item</b>
<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>

<?php $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ($iterator = $_l->its[] = new Latte\Runtime\CachingIterator([1, 2, 3]) as $foo) { ?>
<p<?php if ($_l->tmp = array_filter([$iterator->even ? 'even' : NULL])) echo ' class="', Latte\Runtime\Filters::escapeHtmlAttr(implode(" ", array_unique($_l->tmp))), '"' ?>
><?php echo Latte\Runtime\Filters::escapeHtmlText($foo) ?></p>
<?php $iterations++; } array_pop($_l->its); $iterator = end($_l->its) ?>

<?php $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ([0] as $foo) { if (1) { $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ([1] as $foo) { if ($_l->ifs[] = (0)) { ?>
<span><?php } $iterations++; } $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ([2] as $foo) { if (2) { ?>
Hello<?php } $iterations++; } $iterations = 0; if (isset($template->foo)) trigger_error('Variable $foo overwritten in foreach.', E_USER_NOTICE); foreach ([1] as $foo) { if (array_pop($_l->ifs)) { ?></span>
<?php } $iterations++; } } $iterations++; } ?>


<ul title="foreach break">
<?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ;if (TRUE) { echo "</li>\n"; break; } ?></li>
<?php $iterations++; } ?>
</ul>

<ul title="foreach continue">
<?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ;if (TRUE) { echo "</li>\n"; continue; } ?></li>
<?php $iterations++; } ?>
</ul>


<ul title="inner foreach break">
	<li><?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { echo Latte\Runtime\Filters::escapeHtmlText($person) ;if (TRUE) break ;$iterations++; } ?></li>
</ul>

<ul title="inner foreach continue">
	<li><?php $iterations = 0; if (isset($template->person)) trigger_error('Variable $person overwritten in foreach.', E_USER_NOTICE); foreach ($people as $person) { echo Latte\Runtime\Filters::escapeHtmlText($person) ;if (TRUE) continue ;$iterations++; } ?></li>
</ul>

<?php $_l->switch[] = (2); if (FALSE) { } elseif (end($_l->switch) === ('x')) { ?>x
<?php } elseif (end($_l->switch) === (2)) { ?>y
<?php } else { ?>z
<?php } array_pop($_l->switch) ?>

<?php echo $template->nl2br("\n") ?>



<button></button>

<button></button> xx
<?php
%A%
