<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'static' => ['blockStatic', 'html'],
	];


	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
// template extending

$this->local->extends = empty($this->global->extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $this->global->extended = TRUE;

if ($this->local->extends) { ob_start(function () {});}

// main template
$var = 10 ?>

<?php if ($this->local->extends) { ob_end_clean(); return $this->renderChildTemplate($this->local->extends, get_defined_vars()); }
call_user_func(reset($_b->blocks['static']), $_b, get_defined_vars())  ?>


<?php %a% foreach ($iterator = $this->local->its[] = new Latte\Runtime\CachingIterator(['dynamic', 'static']) as $name) { Latte\Macros\BlockMacrosRuntime::checkType('html', $_b->types, $name);$_b->blocks[$name][] = [$this, 'blockName']; call_user_func(reset($_b->blocks[$name]), $_b, get_defined_vars()) ?>

<?php $iterations++; } array_pop($this->local->its); $iterator = end($this->local->its) ?>

<?php if ('html' !== $_b->types['dynamic']) { trigger_error('Incompatible context for including block dynamic.', E_USER_WARNING); }
Latte\Macros\BlockMacrosRuntime::callBlock($_b, 'dynamic', ['var' => 20] + $this->params) ?>

<?php if ('html' !== $_b->types['static']) { trigger_error('Incompatible context for including block static.', E_USER_WARNING); }
call_user_func(reset($_b->blocks['static']), $_b, ['var' => 30] + get_defined_vars()) ?>

<?php if ('html' !== $_b->types[$name]) { trigger_error('Incompatible context for including block $name.', E_USER_WARNING); }
Latte\Macros\BlockMacrosRuntime::callBlock($_b, $name, ['var' => 40] + $this->params) ?>

<?php Latte\Macros\BlockMacrosRuntime::checkType('html', $_b->types, "word$name");$_b->blocks["word$name"][] = [$this, 'blockWord_name']; call_user_func(reset($_b->blocks["word$name"]), $_b, get_defined_vars()) ?>

<?php Latte\Macros\BlockMacrosRuntime::checkType('html', $_b->types, "word$name");$_b->blocks["word$name"][] = [$this, 'blockWord_name_%h%']; call_user_func(reset($_b->blocks["word$name"]), $_b, get_defined_vars()) ?>

<?php
	}


	function blockName($_b, $_args)
	{
		extract($_args)
?>
		Dynamic block #<?php echo LFilters::escapeHtmlText($var) ?>

<?php
	}


	function blockWord_name($_b, $_args)
	{
		extract($_args);

	}


	function blockWord_name_%h%($_b, $_args)
	{
		extract($_args);

	}


	function blockStatic($_b, $_args)
	{
		extract($_args)
?>	Static block #<?php echo LFilters::escapeHtmlText($var) ?>

<?php
	}

}
