<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'test' => ['blockTest', 'html'],
	];


	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
// template extending

$this->local->extends = empty($this->global->extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $this->global->extended = TRUE;

if ($this->local->extends) { ob_start(function () {});}

// main template
?>

<?php $var = 10 ?>

<?php if ($this->local->extends) { ob_end_clean(); return $this->renderChildTemplate($this->local->extends, get_defined_vars()); } ?>

<?php if ('html' !== $_b->types['test']) { trigger_error('Incompatible context for including block test.', E_USER_WARNING); }
call_user_func(reset($_b->blocks['test']), $_b, ['var' => 20] + get_defined_vars()) ;
	}


	function blockTest($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v
?>	This is definition #<?php echo LFilters::escapeHtmlText($var) ?>

<?php
	}

}
