<?php
%A%

class Template%a% extends Latte\Template
{
	public $contentType = 'xml';


	function render()
	{
%A%?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<script><?php
		if (1) {
			?><meta /><?php
		}
		?>
</script>

<?php header('Content-Type: application/xml; charset=utf-8') ?>

<ul>
	<li>Escaped: <?php echo LFilters::escapeXml($hello) ?></li>
	<li>Non-escaped: <?php echo $hello ?></li>
	<li>Escaped expression: <?php echo LFilters::escapeXml('<' . 'b' . '>hello' . '</b>') ?></li>
	<li>Non-escaped expression: <?php echo '<' . 'b' . '>hello' . '</b>' ?></li>
	<li>Array access: <?php echo LFilters::escapeXml($people[1]) ?></li>
	<li>Html: <?php echo LFilters::escapeXml($el) ?></li>
</ul>

<style type="text/css">
<!--
#<?php echo LFilters::escapeHtmlComment($id) ?> {
	background: blue;
}
-->
</style>


<script>
<!--
var html = <?php echo LFilters::escapeHtmlComment($el) ?>;
-->
</script>


<p onclick =
'alert(<?php echo LFilters::escapeXml($id) ?>);alert("hello");'
 title='<?php echo LFilters::escapeXml($id) ?>"'
 style =
 "color:<?php echo LFilters::escapeXml($id) ?>;'"
 alt='<?php echo LFilters::escapeXml($el) ?>'
 onfocus="alert(<?php echo LFilters::escapeXml($el) ?>)"
>click on me</p>


<!-- <?php echo LFilters::escapeHtmlComment($comment) ?> -->


</ul>


<ul>
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			?>	<li><?php echo LFilters::escapeXml($person) ?></li>
<?php
			$iterations++;
		}
		?>
</ul>

<?php
		if (true) {
			?><p>
	<div><p>true</div>
</p>
<?php
		}
		?>

<input/> <input />

<p val = <?php
		if (true) {
			?>"a"<?php
		}
		else {
			?>"b"<?php
		}
		?>> </p>

<p val = <?php echo LFilters::escapeXmlAttrUnquoted($xss) ?> val2=<?php echo LFilters::escapeXmlAttrUnquoted($mxss) ?>> </p>

<p onclick = <?php echo LFilters::escapeXmlAttrUnquoted($xss) ?>> </p>

<p val = /><?php echo LFilters::escapeXml($xss) ?></p>
<?php
	}

}
