<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'title' => 'blockTitle',
		'sidebar' => 'blockSidebar',
	];

	public $blockTypes = [
		'title' => 'html',
		'sidebar' => 'html',
	];


	function render()
	{
		foreach ($this->params as $__k => $__v) $$__k = $__v; unset($__k, $__v);

// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $this->initialize('html')
;
// prolog Latte\Macros\BlockMacros
// template extending

$_l->extends = empty($_g->extended) && isset($_control) && $_control instanceof Nette\Application\UI\Presenter ? $_control->findLayoutTemplateFile() : NULL; $_g->extended = TRUE;

if ($_l->extends) { ob_start(function () {});}

// main template
extract(['class' => NULL, 'namespace' => NULL, 'top' => TRUE], EXTR_SKIP) ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<link rel="stylesheet" href="style.css">
	<title><?php if ($_l->extends) { ob_end_clean(); return $this->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_b->blocks['title']), $_b, get_defined_vars())  ?></title>
</head>

<body>
	<div id="sidebar">
<?php call_user_func(reset($_b->blocks['sidebar']), $_b, get_defined_vars())  ?>
	</div>

	<div id="content">
<?php if ('html' !== $_b->types['content']) { trigger_error('Incompatible context for including block content.', E_USER_WARNING); }
Latte\Macros\BlockMacrosRuntime::callBlock($_b, 'content', $this->params) ?>
	</div>
</body>
</html>
<?php
	}


	function blockTitle($_b, $_args)
	{
?>My website<?php
	}


	function blockSidebar($_b, $_args)
	{
?>		<ul>
			<li><a href="/">Homepage</a></li>
			<li><a href="/contact">Contact</a></li>
		</ul>
<?php
	}

}
