<?php
%A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'static' => 'blockStatic',
	];

	public $blockTypes = [
		'static' => 'html',
	];


	function render()
	{
%A%
		// main template
		?>

<?php
		call_user_func(reset($this->blockQueue['static']), get_defined_vars());
		?>


<?php
		$iterations = 0;
		%a%
		foreach ($iterator = $this->local->its[] = new Latte\Runtime\CachingIterator(['dynamic', 'static']) as $name) {
			$this->checkBlockContentType('html', $name);
			$this->blockQueue[$name][] = [$this, 'blockName'];
			call_user_func(reset($this->blockQueue[$name]), get_defined_vars()) ?>

<?php
			$iterations++;
		}
		array_pop($this->local->its);
		$iterator = end($this->local->its) ?>

<?php
		if ('html' !== $this->blockTypes['dynamic']) {
			trigger_error('Incompatible context for including block dynamic.', E_USER_WARNING);
		}
		$this->renderBlock('dynamic', ['var' => 20] + $this->params) ?>

<?php
		if ('html' !== $this->blockTypes['static']) {
			trigger_error('Incompatible context for including block static.', E_USER_WARNING);
		}
		call_user_func(reset($this->blockQueue['static']), ['var' => 30] + get_defined_vars()) ?>

<?php
		if ('html' !== $this->blockTypes[$name]) {
			trigger_error('Incompatible context for including block $name.', E_USER_WARNING);
		}
		$this->renderBlock($name, ['var' => 40] + $this->params) ?>

<?php
		$this->checkBlockContentType('html', "word$name");
		$this->blockQueue["word$name"][] = [$this, 'blockWord_name'];
		call_user_func(reset($this->blockQueue["word$name"]), get_defined_vars()) ?>

<?php
		$this->checkBlockContentType('html', "word$name");
		$this->blockQueue["word$name"][] = [$this, 'blockWord_name_%h%'];
		call_user_func(reset($this->blockQueue["word$name"]), get_defined_vars()) ?>

<?php
	}


	function prepare()
	{
		extract($this->params);
		$var = 10;
		return get_defined_vars();
	}


	function blockName($_args)
	{
		extract($_args);
		?>		Dynamic block #<?php echo LFilters::escapeHtml($var) ?>

<?php
	}


	function blockWord_name($_args)
	{
		extract($_args);

	}


	function blockWord_name_%h%($_args)
	{
		extract($_args);

	}


	function blockStatic($_args)
	{
		extract($_args);
		?>	Static block #<?php echo LFilters::escapeHtml($var) ?>

<?php
	}

}
