<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		?><p>Included file #2 (<?php echo LFilters::escapeHtmlText($localvar) ?>, <?php echo LFilters::escapeHtmlText($hello) ?>)</p>

Parent: <?php echo LFilters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) ?>/<?php
		echo LFilters::escapeHtmlText($this->getReferenceType()) ?>

<?php
	}

}
