<?php
// source: %a%
%A%
// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $template->initialize('%[a-z0-9]+%', 'html')
;
//
// main template
//
?>

<?php ob_start(function () {}); $_b->templates['%[a-z0-9]+%']->renderChildTemplate('includeblock.inc.latte', get_defined_vars()); echo rtrim(ob_get_clean()) ?>


<?php Latte\Macros\BlockMacrosRuntime::callBlock($_b, 'test', $template->getParameters()) ;
%A%
