<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
// template extending

$_l->extends = "inheritance.parent2.latte"; $_g->extended = TRUE;

if ($_l->extends) { ob_start(function () {});}

// main template ?>
This should be erased
<?php $foo = 1 ;
// epilog Latte\Macros\BlockMacros
if ($_l->extends) { ob_end_clean(); return $this->renderChildTemplate($_l->extends, get_defined_vars());}

	}

}
