<?php
%A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'test' => 'blockTest',
	];

	public $blockTypes = [
		'test' => 'html',
	];


	function render()
	{
%A%
		// main template
		?>

	<?php
	}


	function blockTest($_args)
	{
		extract($_args);
		?>	Parent: <?php echo LR\Filters::escapeHtml(basename($this->getReferringTemplate()->getName())) ?>/<?php
		echo LR\Filters::escapeHtml($this->getReferenceType()) ?>

<?php
	}

}
