<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
<?php ob_start(function () {}); $this->createTemplate("inc", get_defined_vars(), "includeblock", 'html')->render(); ob_end_clean(); if ('html' !== $this->blockTypes['test']) { trigger_error('Incompatible context for including block test.', E_USER_WARNING); }
$this->renderBlock('test', $this->params) ?>
	<?php
	}

}
