<?php
%A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		if (isset($this->blockTypes['test']) && $this->blockTypes['test'] !== 'html') {
			trigger_error('Incompatible context for including block test.', E_USER_WARNING);
		}
		$this->renderBlock('test', $this->params) ?>	<?php
	}


	function prepare()
	{
		extract($this->params);
		$this->createTemplate("inc", [], "import")->render();
		return get_defined_vars();
	}

}
