<?php
%A%
?>
<ul>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($hello->{'item'}) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText(function(){}) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText(function(){return}) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText(function() { return; }) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->upper(function(){return})) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->upper(function() { return; })) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->upper(function() { return; }, $item->{10})) ?></li>
</ul>
<?php
%A%
