<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
	];


	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
// template extending

$this->local->extends = "inheritance.parent2.latte"; $this->global->extended = TRUE;

if ($this->local->extends) { ob_start(function () {});}

// main template ?>
This should be erased
<?php $foo = 1 ;
// epilog Latte\Macros\BlockMacros
if ($this->local->extends) { ob_end_clean(); return $this->renderChildTemplate($this->local->extends, get_defined_vars());}

	}

}
