<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'content' => 'blockContent',
		'title' => 'blockTitle',
		'sidebar' => 'blockSidebar',
	];


	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
// template extending

$_l->extends = "inheritance.parent.latte"; $_g->extended = TRUE;

if ($_l->extends) { ob_start(function () {});}

// main template ?>


<?php if ($_l->extends) { ob_end_clean(); return $this->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_b->blocks['content']), $_b, get_defined_vars())  ?>


<?php call_user_func(reset($_b->blocks['sidebar']), $_b, get_defined_vars()) ;
	}


	function blockContent($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v
?>	<h1><?php call_user_func(reset($_b->blocks['title']), $_b, get_defined_vars())  ?></h1>

	<ul>
<?php %a% foreach ($people as $person) { ?>
		<li><?php echo LFilters::escapeHtmlText($person) ?></li>
<?php $iterations++; } ?>
	</ul>
<?php
	}


	function blockTitle($_b, $_args)
	{	?>Homepage <?php
	}


	function blockSidebar($_b, $_args)
	{

	}

}
