<?php
// source: %a%
%A%
// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $template->initialize('%[a-z0-9]+%', 'html')
;
//
// main template
//
?>
<span title=<?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr($x), '"' ?>></span>

<span title=<?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr($x), '"' ?> <?php echo '"', Latte\Runtime\Filters::escapeHtmlAttr($x), '"' ?>></span>
<?php
%A%
