<?php
%A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
<?php
		ob_start(function () {});
		$this->createTemplate('subdir/include1.latte' . '', ['localvar' => 10] + $this->params, "include")->renderToContentType('html');
		$_fi = new LR\FilterInfo('html');
		echo LR\Filters::convertTo($_fi, 'html', $this->filters->filterContent('indent', $_fi, ob_get_clean())) ?>

<?php
	}

}
