<?php
%A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'bl' => 'blockBl',
	];

	public $blockTypes = [
		'bl' => 'html',
	];


	function render()
	{
%A%

<p<?php
		echo LR\Filters::htmlAttributes(['title' => 'hello', 'lang' => isset($lang) ? $lang : NULL]);
		?>> </p>



<?php
		$iterations = 0;
		%a%
		foreach ($iterator = $this->global->its[] = new LR\CachingIterator([1,2,3]) as $foo) {
			?>	<b<?php if ($_tmp = array_filter([$iterator->even ? 'even' : NULL])) echo ' class="', LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))), '"' ?>>item</b>
<?php
			$iterations++;
		}
		array_pop($this->global->its);
		$iterator = end($this->global->its);
		?>

<?php
		$iterations = 0;
		%a%
		foreach ($iterator = $this->global->its[] = new LR\CachingIterator([1, 2, 3]) as $foo) {
			?><p<?php if ($_tmp = array_filter([$iterator->even ? 'even' : NULL])) echo ' class="', LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))), '"' ?>><?php
			echo LR\Filters::escapeHtml($foo) ?></p>
<?php
			$iterations++;
		}
		array_pop($this->global->its);
		$iterator = end($this->global->its);
		?>

<p<?php if ($_tmp = array_filter(['foo', (false ? 'first' : NULL), 'odd', (true ? 'foo' : 'bar')])) echo ' class="', LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))), '"' ?>>n:class</p>

<p<?php if ($_tmp = array_filter([false ? 'first' : NULL])) echo ' class="', LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))), '"' ?>>n:class empty</p>



<?php
		call_user_func(reset($this->blockQueue['bl']), get_defined_vars());
		?>





<ul title="foreach">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			?>	<li><?php echo LR\Filters::escapeHtml($person) ?></li>
<?php
			$iterations++;
		}
		?>
</ul>

<ul title="foreach">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			?>	<li>
		<?php echo LR\Filters::escapeHtml($person) ?>

	</li>
<?php
			$iterations++;
		}
		?>
</ul>

<ul title="inner foreach">
	<li>
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			?>		<?php echo LR\Filters::escapeHtml($person) ?>

<?php
			$iterations++;
		}
		?>	</li>
</ul>

<ul title="tag if">
<?php
		if ($this->global->ifs[] = (true)) {
			?>	<li>
<?php
		}
		?>		<?php echo LR\Filters::escapeHtml($person) ?>

<?php
		if (array_pop($this->global->ifs)) {
			?>	</li>
<?php
		}
		?>
</ul>

<ul title="for">
<?php
		for ($i=0;
		$i<3;
		$i++) {
			?>	<li><?php echo LR\Filters::escapeHtml($i) ?></li>
<?php
		}
		?>
</ul>

<ul title="white">
<?php
		while (--$i>0) {
			?>	<li><?php echo LR\Filters::escapeHtml($i) ?></li>
<?php
		}
		?>
</ul>

<?php
		if (true) {
			?><p>
	<div><p>true</div>
</p>
<?php
		}
		?>

<?php
		if (true) {
			?><p>
	<div><p>true</p></div>
</p>
<?php
		}
		?>

<?php
		if (false) {
			?><p>
	<div><p>false</div>
</p>
<?php
		}
		?>

<?php
		if (false) {
			?><p>
	<div><p>false</p></div>
</p>
<?php
		}
		?>

<?php
		if (strlen('{$name}') > 5) {
			?><p>noLatte</p>
<?php
		}
		?>

<ul title="if + foreach">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			if (strlen($person)===4) {
				?>	<li><?php echo LR\Filters::escapeHtml($person) ?></li>
<?php
			}
			$iterations++;
		}
		?>
</ul>

<ul title="if + inner-if + inner-foreach">
<?php
		if (empty($iterator)) {
			?>	<li><?php
			$iterations = 0;
			%a%
			foreach ($people as $person) {
				if (strlen($person)===4) {
					echo LR\Filters::escapeHtml($person);
				}
				$iterations++;
			}
			?></li>
<?php
		}
		?>
</ul>

<ul title="inner-if + inner-foreach">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			if (strlen($person)===4) {
				?>	<li><?php echo LR\Filters::escapeHtml(call_user_func($this->filters->lower, $person)) ?></li>
<?php
			}
			$iterations++;
		}
		?></ul>

<?php
		if ($this->global->ifs[] = (true)) {
			?><b><?php
		}
		?>bold<?php
		if (array_pop($this->global->ifs)) {
			?></b><?php
		}
		?> <?php
		if ($this->global->ifs[] = (false)) {
			?><b><?php
		}
		?>normal<?php
		if (array_pop($this->global->ifs)) {
			?></b>
<?php
		}
		?>

<?php
		if ($this->global->ifs[] = (true)) {
			?><b<?php if ($_tmp = array_filter(['first'])) echo ' class="', LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))), '"' ?>><?php
		}
		?>bold<?php
		if (array_pop($this->global->ifs)) {
			?></b>
<?php
		}
		?>

<meta>
<?php
		if (true) {
			?><meta>
<?php
		}
		if ($this->global->ifs[] = (true)) {
			?><meta>
<?php
		}
		if (array_pop($this->global->ifs)) {
		}
		?>
<meta>
<?php
		if (true) {
		}
		?><meta>

<?php
		$iterations = 0;
		%a%
		foreach ([0] as $foo) {
			if (1) {
				$iterations = 0;
				%a%
				foreach ([1] as $foo) {
					if ($this->global->ifs[] = (0)) {
						?><span><?php
					}
					$iterations++;
				}
				$iterations = 0;
				%a%
				foreach ([2] as $foo) {
					if (2) {
						?>Hello<?php
					}
					$iterations++;
				}
				$iterations = 0;
				%a%
				foreach ([1] as $foo) {
					if (array_pop($this->global->ifs)) {
						?></span>
<?php
					}
					$iterations++;
				}
			}
			$iterations++;
		}
		?>


<ul title="foreach break">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			?>	<li><?php
			echo LR\Filters::escapeHtml($person);
			if (TRUE) {
				echo "</li>\n";
				break;
			}
			?></li>
<?php
			$iterations++;
		}
		?>
</ul>

<ul title="foreach continue">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			?>	<li><?php
			echo LR\Filters::escapeHtml($person);
			if (TRUE) {
				echo "</li>\n";
				continue;
			}
			?></li>
<?php
			$iterations++;
		}
		?>
</ul>


<ul title="inner foreach break">
	<li><?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			echo LR\Filters::escapeHtml($person);
			if (TRUE) break;
			$iterations++;
		}
		?></li>
</ul>

<ul title="inner foreach continue">
	<li><?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			echo LR\Filters::escapeHtml($person);
			if (TRUE) continue;
			$iterations++;
		}
		?></li>
</ul>
<?php
	}


	function blockBl($_args)
	{
		extract($_args);
		?><ul title="block + if + foreach">
<?php
		$iterations = 0;
		%a%
		foreach ($people as $person) {
			if (strlen($person)===4) {
				?>	<li><?php echo LR\Filters::escapeHtml($person) ?></li>
<?php
			}
			$iterations++;
		}
		?>
</ul>
<?php
	}

}
