<?php
// source: %a%
%A%
// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $template->initialize('%[a-z0-9]+%', 'html')
;
//
// main template
//
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<ul>
<?php $iterations = 0; foreach ($people as $person) { ?>
	<li><?php echo Latte\Runtime\Filters::escapeHtml($template->upper($person), ENT_NOQUOTES) ?></li>
<?php $iterations++; } ?>
{* comment latte *}
</ul>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<p>Default: <?php echo Latte\Runtime\Filters::escapeHtml($person, ENT_NOQUOTES) ?></p>

<p>Default: {$person}</p>


<?php
%A%
