<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'test' => 'blockTest',
	];

	public $blockTypes = [
		'test' => 'html',
	];


	function render()
	{
%A%
		// main template

	}


	function blockTest($_args)
	{
		extract($_args);
		?>	Parent: <?php echo LFilters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) ?>/<?php
		echo LFilters::escapeHtmlText($this->getReferenceType()) ?>

<?php
	}

}
