<?php
// source: %A%

class Template%a% extends Latte\Template
{
	public $blocks = [
		'content' => ['blockContent', 'html'],
	];


	function render()
	{
%A%
// main template ?>

<?php if ($this->tryRenderParent(get_defined_vars())) return;call_user_func(reset($this->blockQueue['content']), get_defined_vars()) ;
	}


	function getParentName()
	{
		%A%extract($this->params); return $ext;%A%
	}


	function blockContent($_args)
	{	?>	Content
<?php
	}

}
