<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'test' => 'blockTest',
	];

	public $blockTypes = [
		'test' => 'html',
	];


	function render()
	{
%A%
		// main template
?>

	<?php
	}


	function blockTest($_args)
	{
		extract($_args);
		?>	Parent: <?php echo LR\Filters::escapeHtml(basename($this->getReferringTemplate()->getName())) /* line 3 */ ?>/<?php
		echo LR\Filters::escapeHtml($this->getReferenceType()) /* line 3 */ ?>

<?php
	}

}
