<?php
// source: %a%
%A%
// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $template->initialize('%[a-z0-9]+%', 'html')
;
//
// main template
//
?>
<span title=<?php echo Latte\Runtime\Filters::escapeHtmlAttrUnquoted($x) ?>></span>

<span title=<?php echo Latte\Runtime\Filters::escapeHtmlAttrUnquoted($x) ?> <?php echo Latte\Runtime\Filters::escapeHtmlAttrUnquoted($x) ?>></span>

<span <?php echo Latte\Runtime\Filters::escapeHtmlAttrUnquoted('title') ?>=<?php echo Latte\Runtime\Filters::escapeHtmlAttrUnquoted($x) ?>></span>
<?php
%A%
