<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'content' => 'blockContent',
	];

	public $blockTypes = [
		'content' => 'html',
	];


	function render()
	{
%A%
<?php
		$this->renderBlock('content', get_defined_vars());
		?>	<?php
	}


	function prepare()
	{
		extract($this->params);
		$this->parentName = $ext;
		return get_defined_vars();
	}


	function blockContent($_args)
	{
?>	Content
<?php
	}

}
