<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
// prolog Latte\Macros\BlockMacros
$_b->blocks['content'][] = [$this, 'block_content_%h%'];

$_b->blocks['title'][] = [$this, 'block_title_%h%'];

$_b->blocks['sidebar'][] = [$this, 'block_sidebar_%h%'];

// template extending

$_l->extends = "inheritance.parent.latte"; $_g->extended = TRUE;

if ($_l->extends) { ob_start(function () {});}

// main template ?>


<?php if ($_l->extends) { ob_end_clean(); return $template->renderChildTemplate($_l->extends, get_defined_vars()); }
call_user_func(reset($_b->blocks['content']), $_b, get_defined_vars())  ?>


<?php call_user_func(reset($_b->blocks['sidebar']), $_b, get_defined_vars()) ;
	}


	function block_content_%h%($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v
?>	<h1><?php call_user_func(reset($_b->blocks['title']), $_b, get_defined_vars())  ?></h1>

	<ul>
<?php %a% foreach ($people as $person) { ?>
		<li><?php echo Latte\Runtime\Filters::escapeHtmlText($person) ?></li>
<?php $iterations++; } ?>
	</ul>
<?php
	}


	function block_title_%h%($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v
?>Homepage <?php
	}


	function block_sidebar_%h%($_b, $_args)
	{
		unset($_args["this"]); foreach ($_args as $__k => $__v) $$__k = $__v;

	}

}
