<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%?>
<ul>
	<li>lower: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->lower($hello)) ?></li>
	<li>upper: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->upper($hello)) ?></li>
	<li>lower & capitalize: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->capitalize($template->lower($hello))) ?></li>
	<li>nl2br: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->nl2br($hello)) ?></li>
	<li>truncate: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->lower($template->truncate($hello, "10 "))) ?></li>
	<li>date: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->date($date, '%d.%m.%Y %H:%M:%S')) ?></li>
	<li>translated: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->truncate($template->translate($hello), 3)) ?></li>
	<li>Translated HTML: <?php ob_start(function () {}) ?>ahoj<?php echo Latte\Runtime\Filters::escapeHtmlText($template->translate(ob_get_clean())) ?></li>
	<li>Translated HTML: <?php ob_start(function () {}) ?>ahoj<?php echo Latte\Runtime\Filters::escapeHtmlText($template->translate(ob_get_clean())) ?></li>
	<li>Translated HTML: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->translate('ahoj|ahojahojahojahoj')) ?></li>
	<li>spaces: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->types($hello , '' , "" , "$hello" )) ?></li>
	<li>dynamic: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->dynamic($hello)) ?>
 <?php echo Latte\Runtime\Filters::escapeHtmlText($template->dynamic2($hello)) ?></li>
</ul>

<ul>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->h2($template->h1($hello))) ?></li>
	<li><?php echo $template->h2($template->h1($hello)) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->h1($template->h2($hello))) ?></li>
	<li><?php echo $template->h1($template->h2($hello)) ?></li>
</ul>

<ul>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->types($hello*0, 0, 0.0, "0")) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->types($hello*1, 1, "1")) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->types($hello, true, null, false)) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->types($hello, TRUE, NULL, FALSE)) ?></li>
	<li><?php echo Latte\Runtime\Filters::escapeHtmlText($template->types($hello, '', "", "$hello")) ?></li>
</ul>



<?php ob_start(function () {}) ?>  <a   href="#"
> test</a

>
AŠA

<script>
// comment
alert();
</script>
<?php echo $template->strip(ob_get_clean()) ?>




<?php ob_start(function () {}) ?>
<ul>
	<li>lower: <?php echo Latte\Runtime\Filters::escapeHtmlText($template->lower($hello)) ?></li>
</ul>
<?php $capture = ob_get_clean() ?>

<p>
Captured: <?php echo Latte\Runtime\Filters::escapeHtmlText($capture) ?>

</p>


<?php ob_start(function () {}) ?>
Hello
<?php $capture = $template->upper(ob_get_clean()) ?>

<p>
Captured with modifier: <?php echo Latte\Runtime\Filters::escapeHtmlText($capture) ?>

</p>



<p>
Nested blocks: <?php ob_start(function () {}) ?> Outer   <?php ob_start(function () {}) ?>
 Inner Block <?php echo $template->upper(ob_get_clean()) ?>  Block <?php echo $template->truncate(ob_get_clean(), 20) ?>

</p>
<?php
	}

}
