<?php
%A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%?>
<p>Included file #1</p>

<?php $this->createTemplate("include2.latte", ['localvar' => 20] + $this->params, "include", 'html')->render() ?>

<?php $this->createTemplate("../include3.latte", $this->params, "include", 'html')->render() ?>

<textarea>
pre
</textarea>

Parent: <?php echo LFilters::escapeHtmlText(basename($this->getReferringTemplate()->getName())) ?>/<?php
		echo LFilters::escapeHtmlText($this->getReferenceType()) ?>

<?php
	}

}
