<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'block1' => 'blockBlock1',
		'_snippet' => 'blockSnippet',
		'_outer' => 'blockOuter',
		'block2' => 'blockBlock2',
	];

	public $blockTypes = [
		'block1' => 'html',
		'_snippet' => 'html',
		'_outer' => 'html',
		'block2' => 'html',
	];


	function render()
	{
%A%
		$this->renderBlock('block1', get_defined_vars());
?>


<div id="<?php echo htmlSpecialChars($this->global->snippetDriver->getHtmlId('outer')) ?>"><?php $this->renderBlock('_outer', $this->params) ?></div><?php

	}


	function blockBlock1($_args)
	{
		extract($_args);
		?><div<?php echo ' id="' . htmlSpecialChars($this->global->snippetDriver->getHtmlId('snippet')) . '"' ?>>
<?php $this->renderBlock('_snippet', $this->params) ?>
</div>
<?php

	}


	function blockSnippet($_args)
	{
		extract($_args);
		$this->global->snippetDriver->enter("snippet", "static");
?>		static
<?php
		$this->global->snippetDriver->leave();

	}


	function blockOuter($_args)
	{
		extract($_args);
		$this->global->snippetDriver->enter("outer", "static");
?>
begin
<?php
		$this->renderBlock('block2', get_defined_vars());
?>
end
<?php
		$this->global->snippetDriver->leave();

	}


	function blockBlock2($_args)
	{
		extract($_args);
		?><div<?php echo ' id="' . htmlSpecialChars($this->global->snippetDriver->getHtmlId("inner-$id")) . '"' ?>>
<?php
		$this->global->snippetDriver->enter("inner-$id", "dynamic");
?>		dynamic
<?php
		$this->global->snippetDriver->leave();
?></div>
<?php

	}

}
