<?php
// source: %a%
%A%
// prolog Latte\Macros\CoreMacros
list($_b, $_g, $_l) = $template->initialize('%[a-z0-9]+%', 'html')
;
//
// main template
//
?>
<span title=<?php echo '"', Latte\Runtime\Filters::escapeHtml($x, ENT_COMPAT), '"' ?>></span>

<span title=<?php echo '"', Latte\Runtime\Filters::escapeHtml($x, ENT_COMPAT), '"' ?>
 <?php echo Latte\Runtime\Filters::escapeName($x) ?>></span>

<span <?php echo Latte\Runtime\Filters::escapeName($x) ?>=<?php echo '"', Latte\Runtime\Filters::escapeHtml($x, ENT_COMPAT), '"' ?>
 <?php echo Latte\Runtime\Filters::escapeName($x) ?>=<?php echo '"', Latte\Runtime\Filters::escapeHtml($x, ENT_COMPAT), '"' ?>></span>
<?php
%A%
