<?php
%A%

class Template%a% extends Latte\Runtime\Template
{
	public $blocks = [
		'title' => 'blockTitle',
		'content' => 'blockContent',
	];

	public $blockTypes = [
		'title' => 'html',
		'content' => 'html',
	];


	function render()
	{
%A%
<?php
		call_user_func(reset($this->blockQueue['title']), get_defined_vars());
?>

<?php
		call_user_func(reset($this->blockQueue['content']), get_defined_vars());
		?>	<?php
	}


	function prepare()
	{
		extract($this->params);
		$this->parentName = "parent";
		$this->createTemplate("inc", $this->params, "import")->render();
		ob_start(function () {});
		$this->createTemplate("inc", get_defined_vars(), "includeblock")->renderToContentType('html');
		echo rtrim(ob_get_clean());
		return get_defined_vars();
	}


	function blockTitle($_args)
	{
		extract($_args);
		?>Homepage | <?php
		$this->renderBlockParent('title', get_defined_vars());
		$this->renderBlockParent('title', get_defined_vars());

	}


	function blockContent($_args)
	{
		extract($_args);
?>
	<ul>
<?php
		$iterations = 0;
		foreach ($people as $person) {
			?>		<li><?php echo LR\Filters::escapeHtml($person) /* line 12 */ ?></li>
<?php
			$iterations++;
		}
?>
	</ul>
	Parent: <?php echo LR\Filters::escapeHtml(gettype($this->getReferringTemplate())) /* line 15 */ ?>

<?php
	}

}
