<?php
%A%
		echo 'functions

';
		echo LR\Filters::escapeHtmlText(func()) /* line 3 */;
		echo '
';
		echo LR\Filters::escapeHtmlText($this->call('func')()) /* line 4 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call(('fu' . 'nc'))()) /* line 5 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText(\func()) /* line 6 */;
		echo '
';
		echo LR\Filters::escapeHtmlText(ns\func()) /* line 7 */;
		echo '
';
		echo LR\Filters::escapeHtmlText($this->prop(func(), 'prop')->prop) /* line 8 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call(func())()) /* line 9 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call(func( $this->prop($a, 'prop')->prop ))( func() )) /* line 10 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call(func()['x'])()) /* line 11 */;
		echo '
-';
%A%
