<?php
%A%
		echo 'static props

';
		echo LR\Filters::escapeHtmlText($this->prop(\Name\MyClass::class, 'prop')::$prop) /* line 3 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->prop($this->prop(\Name\MyClass::class, 'prop')::$prop, 'x')->x) /* line 4 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->prop(\Name\MyClass::class, 'prop')::$prop[1]) /* line 5 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->prop($this->prop(\Name\MyClass::class, 'prop')::$prop[1], 'x')->x) /* line 6 */;
		echo '
-';
%A%
