<?php
%A%
		echo 'static methods

';
		echo LR\Filters::escapeHtmlText($this->call([MyClass::class, 'method'])()) /* line 3 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call([\Name\MyClass::class, 'method'])()) /* line 4 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call([\Name\MyClass::class, (string) ('method')])()) /* line 5 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call([\Name\MyClass::class, $method])()) /* line 6 */;
		echo '
-';
%A%
