<?php
%A%
		echo 'object methods

';
		echo LR\Filters::escapeHtmlText($this->call([$obj, 'method'])()) /* line 3 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call([$obj, (string) 'method'])()) /* line 4 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call([$obj, $method])()) /* line 5 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call([$obj, 'method'])()) /* line 6 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->call($this->call([$obj, 'method'])())()) /* line 7 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->prop($this->call([$obj, 'method'])(), 'prop')->prop) /* line 8 */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->prop($this->call([$obj, 'method'])(), 'prop')->prop) /* line 9 */;
		echo '
-';
%A%
