<?php
%A%
static methods

<?php echo LR\Filters::escapeHtmlText($this->call([MyClass::class, 'method'])()) /* line 3 */ ?>

<?php echo LR\Filters::escapeHtmlText($this->call([\Name\MyClass::class, 'method'])()) /* line 4 */ ?>

<?php echo LR\Filters::escapeHtmlText($this->call([\Name\MyClass::class, (string) ('method')])()) /* line 5 */ ?>

<?php echo LR\Filters::escapeHtmlText($this->call([\Name\MyClass::class, $method])()) /* line 6 */ ?>

-%A%
