<?php
%A%
static props

<?php echo LR\Filters::escapeHtmlText(\Name\MyClass::CONST) /* line 3 */ ?>

<?php echo LR\Filters::escapeHtmlText($obj::CONST) /* line 4 */ ?>

<?php echo LR\Filters::escapeHtmlText($obj::CONST) /* line 5 */ ?>

<?php echo LR\Filters::escapeHtmlText($this->call(($obj::CONST))()) /* line 6 */ ?>

<?php echo LR\Filters::escapeHtmlText($this->call($obj::CONST[0])()) /* line 7 */ ?>

<?php echo LR\Filters::escapeHtmlText($this->call(CONST[0])()) /* line 8 */ ?>

-%A%
