<?php
%A%
		echo 'optional chaining

';
		echo LR\Filters::escapeHtmlText($this->global->sandbox->prop($obj, 'prop')?->prop) /* line %d% */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->global->sandbox->prop($obj ?? null, 'prop')?->prop) /* line %d% */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->global->sandbox->callMethod($obj, 'bar')?->__invoke()) /* line %d% */;
		echo "\n";
		echo LR\Filters::escapeHtmlText($this->global->sandbox->callMethod($obj ?? null, 'bar')?->__invoke()) /* line %d% */;
		echo '
-';
%A%
