<?php
%A%
final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		1 => ['a' => 'blockA'],
		2 => ['a' => 'blockA1'],
	];


	public function main(): array
	{
		extract($this->params);
		echo "\n";
		$this->enterBlockLayer(1, get_defined_vars()) /* line %d% */;
		$this->createTemplate("import.latte", $this->params, "import")->render() /* line %d% */;
		try {
			$this->createTemplate("embed1.latte", [], "embed")->renderToContentType('html') /* line %d% */;
		} finally {
			$this->leaveBlockLayer();
		}
		return get_defined_vars();
	}


	/** {block a} on line %d% */
	public function blockA(array $ʟ_args): void
	{
		extract(end($this->varStack));
		extract($ʟ_args);
		unset($ʟ_args);

		$this->enterBlockLayer(2, get_defined_vars()) /* line %d% */;
		try {
			$this->createTemplate("embed2.latte", [], "embed")->renderToContentType('html') /* line %d% */;
		} finally {
			$this->leaveBlockLayer();
		}
	}


	/** {block a} on line %d% */
	public function blockA1(array $ʟ_args): void
	{
		echo 'nested embeds A';
	}

}
