<?php
%A%
final class Template%a% extends Latte\Runtime\Template
{
	public const Blocks = [
		'snippet' => ['outer' => 'blockOuter'],
	];


	public function main(): array
	{
%A%
		echo '	';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('outer')), '">';
		$this->renderBlock('outer', [], null, 'snippet') /* line %d% */;
		echo '</div>';
%A%
	}


	public function prepare(): void
	{
%A%
	}


	/** {snippet outer} on line %d% */
	public function blockOuter(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter("outer", 'static') /* line %d% */;
		try {
			echo "\n";
			$iterations = 0;
			foreach (array(1,2,3) as $id) /* line %d% */ {
				echo '		';
				echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId($ʟ_nm = ('inner-' . $id))), '">';
				$this->global->snippetDriver->enter($ʟ_nm, 'dynamic') /* line %d% */;
				try {
					echo '
				#';
					echo LR\Filters::escapeHtmlText($id) /* line %d% */;
					echo "\n";

				} finally {
					$this->global->snippetDriver->leave();
				}

				echo '</div>
';
				$iterations++;
			}


		} finally {
			$this->global->snippetDriver->leave();
		}
	}
}
