<?php
%A%
final class Template%a% extends Latte\Runtime\Template
{
	public const Blocks = [
		'snippet' => ['outer1' => 'blockOuter1'],
	];


	public function main(array $ʟ_args): void
	{
%A%
		echo '	';
		echo '<div id="', htmlspecialchars($this->global->snippetDriver->getHtmlId('outer1')), '">';
		$this->renderBlock('outer1', [], null, 'snippet') /* line %d% */;
		echo '</div>';
	}


	public function prepare(): array
	{
%A%
	}


	/** {snippet outer1} on line %d% */
	public function blockOuter1(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter("outer1", 'static') /* line %d% */;
		try {
			echo "\n";
			$iterations = 0;
			foreach (array(1,2,3) as $id) /* line %d% */ {
				echo '<div';
				echo ' id="', htmlspecialchars($this->global->snippetDriver->getHtmlId($ʟ_nm = "inner-{$id}")), '"';
				echo '>';
				$this->global->snippetDriver->enter($ʟ_nm, 'dynamic') /* line %d% */;
				try {
					echo '
				#';
					echo LR\Filters::escapeHtmlText($id) /* line %d% */;
					echo '
		';

				} finally {
					$this->global->snippetDriver->leave();
				}
				echo '</div>';
				$iterations++;
			}

			echo '	';

		} finally {
			$this->global->snippetDriver->leave();
		}
	}
}
