<?php
%A%
final class Template%a% extends Latte\Runtime\Template
{
	protected const BLOCKS = [
		'snippet' => ['outer' => 'blockOuter', 'gallery' => 'blockGallery'],
	];


	public function main(): array
	{
%A%
		echo '	<div class="test"';
		echo ' id="', htmlspecialchars($this->global->snippetDriver->getHtmlId($ʟ_nm = 'outer')), '"';
		echo '>
';
		$this->renderBlock('outer', [], null, 'snippet');
		echo '	</div>

	<div class="';
		echo LR\Filters::escapeHtmlAttr('class') /* line %d% */;
		echo '"';
		echo ' id="', htmlspecialchars($this->global->snippetDriver->getHtmlId($ʟ_nm = 'gallery')), '"';
		echo '>';
		$this->renderBlock('gallery', [], null, 'snippet');
		echo '</div>
';
%A%
	}


	/** {snippet outer} on line %d% */
	public function blockOuter(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter("outer", 'static') /* line %d% */;
		try {
			echo '	<p>Outer</p>
';
		} finally {
			$this->global->snippetDriver->leave();
		}
	}


	/** {snippet gallery} on line %d% */
	public function blockGallery(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);

		$this->global->snippetDriver->enter("gallery", 'static') /* line %d% */;
		try {

		} finally {
			$this->global->snippetDriver->leave();
		}
	}

}
