<?php
%A%
		$ʟ_switch = (0) /* line %d% */;
		if (in_array($ʟ_switch, [''], true)) /* line %d% */ {
			echo 'string
';
		} elseif (in_array($ʟ_switch, [0.0], true)) /* line %d% */ {
			echo 'flot
';
		} else {
			echo 'def
';
		}
		echo '
---

';
		$ʟ_switch = ('a') /* line %d% */;
		if (in_array($ʟ_switch, [1, 2, 'a'], true)) /* line %d% */ {
			echo 'a
';
		}
		echo '
---

';
		$ʟ_switch = ('a') /* line %d% */;
		echo 'def

---

';
		$ʟ_switch = ('a') /* line %d% */;
%A%
