<?php
%A%
	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);
		/** @var int $intType */
		/** @var int|bool $intBoolType */
		/** @var array<int, string> $arrayType */
%A%
	public function blockTest(array $ʟ_args): void
	{
		extract($this->params);
		extract($ʟ_args);
		unset($ʟ_args);
		/** @var int $intType */
		/** @var int|bool $intBoolType */
		/** @var array<int, string> $arrayType */
%A%